### ISSUE TITLE
Opal with Node: Native does not catch EventEmitter events

### ISSUE THREAD

**Issue by Qqwy** [opal/opal#1082]
Node makes heavy use of objects that inherit from the EventEmitter class (see https://nodejs.org/api/events.html)

An example of Node.js code:

```
var EventEmitter = require('events').EventEmitter;
var radium = new EventEmitter();

radium.on('radiation', function(ray) {
    console.log(ray);
});

setInterval(function() {
    radium.emit('radiation', 'GAMMA');
}, 1000);    
```

This should log the word  'GAMMA' to the console once every second.

This is how I tried to port the code to Opal:

```
`var EventEmitter = require('events').EventEmitter;`
radium = Native(`new EventEmitter()`);

radium.on('radiation')do |ray|
    puts (ray);
end

`setInterval(function() {`
    radium.emit('radiation', 'GAMMA');
`}, 1000);`
```

The Interval is run every second, but the on('radiation') event on the radium object is never triggered.

I have also tried:

```
`var EventEmitter = require('events').EventEmitter;`
radium = Native(`new EventEmitter()`);

Native.call(radium,'on','radiation') do |ray|
    puts (ray);
end

`setInterval(function() {`
    radium.emit('radiation', 'GAMMA');
`}, 1000);`
```

but this does not change the result.

I believe that this is functionality that Native ought to provide.

**Comment by elia** [comment]
If you want to try sending a pull request you can have a look at the implementation of Opal-jquery that does something similar for Dom events

**Comment by elia** [comment]
Closing this, the proposal is still good, although there's also this that can be done quite easily:

```rb
`var EventEmitter = require('events').EventEmitter;`
radium = Native(`new EventEmitter()`);

radium.on('radiation')do |ray|
    puts (ray);
end

`setInterval(function() {
  #{radium.emit('radiation', 'GAMMA')}
}, 1000);`
```

Ouput:
```
opal:master ⤑ pbpaste | opal -rnative -v -                                                                                                             ~/C/opal
Opal v1.0.0
GAMMA
GAMMA
GAMMA
GAMMA
^CTraceback (most recent call last):
	9: from /Users/elia/.rvm/rubies/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'
	8: from /Users/elia/.rvm/rubies/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
	7: from /Users/elia/.rvm/gems/ruby-2.6.2/bin/opal:23:in `<main>'
	6: from /Users/elia/.rvm/gems/ruby-2.6.2/bin/opal:23:in `load'
	5: from /Users/elia/Code/opal/exe/opal:24:in `<top (required)>'
	4: from /Users/elia/Code/opal/lib/opal/cli.rb:62:in `run'
	3: from /Users/elia/Code/opal/lib/opal/cli_runners.rb:69:in `block in legacy_runner'
	2: from /Users/elia/Code/opal/lib/opal/cli_runners/nodejs.rb:32:in `run'
	1: from /Users/elia/Code/opal/lib/opal/cli_runners/nodejs.rb:40:in `system_with_output'
/Users/elia/Code/opal/lib/opal/cli_runners/nodejs.rb:40:in `system': Interrupt
opal:master ⤑                          
```
