### ISSUE TITLE
RUBY_DESCRIPTION not implemented

### ISSUE THREAD

**Issue by PragTob** [opal/opal#1115]
Hi there,

thanks for working on opal. I tried it and noticed that `RUBY_DESCRIPTION` was not implemented.

```
tobi@tobi-desktop ~/github/rubykon $ opal --version
Opal v0.8.0
tobi@tobi-desktop ~/github/rubykon $ opal -e "puts RUBY_DESCRIPTION"

/tmp/opal-nodejs-runner-20150927-4063-1gu6f9w:3611
      throw exception;
            ^
NameError: uninitialized constant Object::RUBY_DESCRIPTION
    at OpalClass.def.$initialize.self [as $new] (/tmp/opal-nodejs-runner-20150927-4063-1gu6f9w:3941:15)
    at Opal.defn.self (/tmp/opal-nodejs-runner-20150927-4063-1gu6f9w:3606:31)
    at def.$const_missing (/tmp/opal-nodejs-runner-20150927-4063-1gu6f9w:1925:19)
    at Opal.get (/tmp/opal-nodejs-runner-20150927-4063-1gu6f9w:75:24)
    at Opal.dynamic_require_severity (/tmp/opal-nodejs-runner-20150927-4063-1gu6f9w:14713:28)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20150927-4063-1gu6f9w:14714:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
tobi@tobi-desktop ~/github/rubykon $ ruby -e "puts RUBY_DESCRIPTION"
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
tobi@tobi-desktop ~/github/rubykon $ rvm use jruby
Using /home/tobi/.rvm/gems/jruby-9.0.1.0
tobi@tobi-desktop ~/github/rubykon $ ruby -e "puts RUBY_DESCRIPTION"
jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 OpenJDK 64-Bit Server VM 24.79-b02 on 1.7.0_79-b14 +jit [linux-amd64]
```

Cheers,
Tobi

**Comment by elia** [comment]
Yeah, I think has been added to master some time after 0.8 has been released :)

https://github.com/opal/opal/blob/master/opal/corelib/constants.rb

**Comment by PragTob** [comment]
Okay, cool thanks - should have tried to check master :)
