### ISSUE TITLE
Unable to run benchmark-ips due to missing modules GC/Math

### ISSUE THREAD

**Issue by PragTob** [opal/opal#1116]
[benchmark-ips](https://github.com/evanphx/benchmark-ips) is an awesome often used gem for benchmarking. I can't seem to get it to work under opal, but maybe I'm doing something terribly wrong as #472 says that the missing Math module thing is fixed. E.g. first it complains about `GC` not being there, when I fixed that it complained about `Math` missing and that doesn't seem to be trivial to fix :)

```
tobi@tobi-desktop ~/github/rubykon $ opal -v
Opal v0.8.0
tobi@tobi-desktop ~/github/rubykon $ opal -e "p GC"

/tmp/opal-nodejs-runner-20150927-4706-10rzhgt:3611
      throw exception;
            ^
NameError: uninitialized constant Object::GC
    at OpalClass.def.$initialize.self [as $new] (/tmp/opal-nodejs-runner-20150927-4706-10rzhgt:3941:15)
    at Opal.defn.self (/tmp/opal-nodejs-runner-20150927-4706-10rzhgt:3606:31)
    at def.$const_missing (/tmp/opal-nodejs-runner-20150927-4706-10rzhgt:1925:19)
    at Opal.get (/tmp/opal-nodejs-runner-20150927-4706-10rzhgt:75:24)
    at Opal.dynamic_require_severity (/tmp/opal-nodejs-runner-20150927-4706-10rzhgt:14713:25)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20150927-4706-10rzhgt:14714:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
tobi@tobi-desktop ~/github/rubykon $ ruby -e "p GC"
GC
tobi@tobi-desktop ~/github/rubykon $ opal -e "p Math"

/tmp/opal-nodejs-runner-20150927-4720-cxinus:3611
      throw exception;
            ^
NameError: uninitialized constant Object::Math
    at OpalClass.def.$initialize.self [as $new] (/tmp/opal-nodejs-runner-20150927-4720-cxinus:3941:15)
    at Opal.defn.self (/tmp/opal-nodejs-runner-20150927-4720-cxinus:3606:31)
    at def.$const_missing (/tmp/opal-nodejs-runner-20150927-4720-cxinus:1925:19)
    at Opal.get (/tmp/opal-nodejs-runner-20150927-4720-cxinus:75:24)
    at Opal.dynamic_require_severity (/tmp/opal-nodejs-runner-20150927-4720-cxinus:14713:25)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20150927-4720-cxinus:14714:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
tobi@tobi-desktop ~/github/rubykon $ ruby -e "p Math"
Math
```

I'd love to have opal work with benchmark-ips so I can see how it fares against cruby, jruby, truffle, rbx and friends :)

Thanks,
Tobi

**Comment by elia** [comment]
Seems to be working on master, just had to install opal from the repo with `rake install` first, otherwise bundler would complain about `benchmark-ips` being out of the bundle

```
opal:master ✨  gem install benchmark-ips                                                                                                                                                                ~/C/opal
Successfully installed benchmark-ips-2.3.0
1 gem installed
opal:master ✨  rake install                                                                                                                                                                             ~/C/opal
opal 0.9.0.dev built to pkg/opal-0.9.0.dev.gem.
opal (0.9.0.dev) installed.
opal:master ✨  opal _0.9.0.dev_ -g benchmark-ips -rbenchmark/ips -e 'Benchmark.ips { |x| x.report("addition") { 1 + 2 } }'                                                                              ~/C/opal
Calculating -------------------------------------
            addition   111.396k i/100ms
-------------------------------------------------
            addition     14.029M (± 8.6%) i/s -     69.288M
opal:master ✨                                                                                                                                                                                           ~/C/opal
```

as a bonus here's the results for MRI 😸:

```
opal:master ✨  ruby -v -rbenchmark/ips -e 'Benchmark.ips { |x| x.report("addition") { 1 + 2 } }'                                                                                                        ~/C/opal
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
Calculating -------------------------------------
            addition   148.229k i/100ms
-------------------------------------------------
            addition     10.592M (± 4.9%) i/s -     52.918M
opal:master ✨                                                                                                                                                                                           ~/C/opal
```
