### ISSUE TITLE
Dup on fixnum

### ISSUE THREAD

**Issue by ryanstout** [opal/opal#1122]
In MRI, if I try to duplicate a fixnum like so:

```ruby
5.dup
```

I get the following:

```TypeError: can't dup Fixnum```

In opal I get: ```0```

Thanks!  Keep up the good work.

**Comment by elia** [comment]
Seems already fixed on master:

```
opal:master ✨  opal _0.9.0.dev_ -ve 'p 4.dup'                                                                                                                             ~/C/opal
Opal v0.9.0.dev

/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20151001-88286-15eigu7:4175
      throw exception;
      ^
TypeError: can't dup Number
    at OpalClass.$new (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20151001-88286-15eigu7:4386:15)
    at Number.$raise (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20151001-88286-15eigu7:4170:31)
    at Number.$dup (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20151001-88286-15eigu7:9609:19)
    at /private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20151001-88286-15eigu7:18551:22
    at Object.<anonymous> (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20151001-88286-15eigu7:18552:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
opal:master ✨  opal _0.8.0_ -ve 'p 4.dup'                                                                                                                                 ~/C/opal
Opal v0.8.0
0
```

**Comment by ryanstout** [comment]
Cool, thanks!
