### ISSUE TITLE
Strange syntax issue with do-blocks inside of methods using prefix `private`

### ISSUE THREAD

**Issue by krainboltgreene** [opal/opal#1130]
```
parse error on value "do" (kDO_BLOCK) :dashboard/component/content:16
.../opal-0.8.0/lib/opal/parser.rb:81:in `on_error'
.../opal-0.8.0/lib/opal/parser.rb:53:in `parse_to_sexp'
.../opal-0.8.0/lib/opal/parser.rb:38:in `parse'
.../opal-0.8.0/lib/opal/compiler.rb:135:in `compile'
.../opal-0.8.0/lib/opal/builder_processors.rb:91:in `compiled'
.../opal-0.8.0/lib/opal/builder_processors.rb:101:in `requires'
.../opal-0.8.0/lib/opal/builder.rb:139:in `process_require'
.../opal-0.8.0/lib/opal/builder.rb:144:in `block in process_requires'
.../opal-0.8.0/lib/opal/builder.rb:144:in `map'
.../opal-0.8.0/lib/opal/builder.rb:144:in `process_requires'
.../opal-0.8.0/lib/opal/builder.rb:139:in `process_require'
.../opal-0.8.0/lib/opal/builder.rb:42:in `block in build_str'
.../opal-0.8.0/lib/opal/builder.rb:42:in `map'
.../opal-0.8.0/lib/opal/builder.rb:42:in `build_str'
.../opal-0.8.0/lib/opal/builder.rb:35:in `build'
.../opal-0.8.0/lib/opal/builder.rb:30:in `build'
```

``` ruby
        private def areas(*components)
          components.map do |component|
            pp("Creating a new area component")
            Component::Area.new(["graph"], component)
          end
        end
```

While I realize `private` is no-op in opal this is syntax that works in CRuby, JRuby, and Rubinius. Removing `private` "fixes" the syntax error. Switching to `{ |...| ... }` "fixes" the syntax error.

**Comment by elia** [comment]
Can confirm it's on master too:

```
pbpaste | be bin/opal -vOc                                                                                                                                 ~/C/opal
Opal v0.9.0.dev
/Users/elia/Code/opal/lib/opal/parser.rb:81:in `on_error': An error occurred while compiling: - (RuntimeError)

parse error on value "do" (kDO_BLOCK) :-:2
Source: -:2:27
          components.map do |component|
~~~~~~~~~~~~~~~~~~~~~~~~~~^
	from /Users/elia/.rvm/gems/ruby-2.2.3/gems/racc-1.4.12/lib/racc/parser.rb:271:in `_racc_do_parse_c'
	from /Users/elia/.rvm/gems/ruby-2.2.3/gems/racc-1.4.12/lib/racc/parser.rb:271:in `do_parse'
	from /Users/elia/Code/opal/lib/opal/parser.rb:53:in `parse_to_sexp'
	from /Users/elia/Code/opal/lib/opal/parser.rb:38:in `parse'
	from /Users/elia/Code/opal/lib/opal/compiler.rb:147:in `compile'
	from /Users/elia/Code/opal/lib/opal/builder_processors.rb:91:in `compiled'
	from /Users/elia/Code/opal/lib/opal/builder_processors.rb:101:in `requires'
	from /Users/elia/Code/opal/lib/opal/builder.rb:41:in `build_str'
	from /Users/elia/Code/opal/lib/opal/cli.rb:112:in `build'
	from /Users/elia/Code/opal/lib/opal/cli.rb:122:in `compiled_source'
	from /Users/elia/Code/opal/lib/opal/cli.rb:126:in `show_compiled_source'
	from /Users/elia/Code/opal/lib/opal/cli.rb:68:in `run'
	from bin/opal:22:in `<main>'
```

**Comment by iliabylich** [comment]
Fixed on the lasest master (most probably with switching to parser in #1465):
``` ruby
private def areas(*components)
  components.map do |component|
    pp("Creating a new area component")
    Component::Area.new(["graph"], component)
  end
end
```
``` js
return self.$private((Opal.defn(Opal.Object, '$areas', TMP_areas_2 = function ːareas($a_rest) {
    var $b, $c, TMP_1, self = this, components;

    var $args_len = arguments.length, $rest_len = $args_len - 0;
    if ($rest_len < 0) { $rest_len = 0; }
    components = new Array($rest_len);
    for (var $arg_idx = 0; $arg_idx < $args_len; $arg_idx++) {
      components[$arg_idx - 0] = arguments[$arg_idx];
    }
    return ($b = ($c = components).$map, $b.$$p = (TMP_1 = function(component){var self = TMP_1.$$s || this;
if (component == null) component = nil;
    
      self.$pp("Creating a new area component");
      return Opal.const_get([Opal.const_get($scopes, 'Component', true, true).$$scope], 'Area', true, true).$new(["graph"], component);}, TMP_1.$$s = self, TMP_1.$$arity = 1, TMP_1), $b).call($c)
  }, TMP_areas_2.$$arity = -1), nil) && 'areas')
```
