### ISSUE TITLE
Calling a method that takes a block after just calling another method that takes a block blows up

### ISSUE THREAD

**Issue by wied03** [opal/opal#1173]
When a method executes a block, unless that method's return value is stored in a local variable first, it cannot be passed to another method as a parameter.

```ruby
def do_ival(something, &block)
  puts "about to call block #{something}"
  block.call
end

def method1
  do_ival(1) do
    puts 'block 1'
    :foo
  end
end

do_ival(method1) do
  puts 'block 2'
end

# this approach works on Opal
# m = method1
# do_ival(m) do
#   puts 'block 2'
# end
```
Output:
```
root@default:/host/opal# bundle exec opal ../bah.rb 
about to call block 1
block 1
about to call block foo

/tmp/opal-nodejs-runner-20151031-75-refeve:4219
      throw exception;
            ^
call: undefined method `call' for nil
    at OpalClass.Opal.defs.self [as $new] (/tmp/opal-nodejs-runner-20151031-75-refeve:4436:15)
    at NilClass.Opal.defn.TMP_1 (/tmp/opal-nodejs-runner-20151031-75-refeve:3032:54)
    at NilClass.method_missing_stub [as $call] (/tmp/opal-nodejs-runner-20151031-75-refeve:886:35)
    at Object.Opal.defn.TMP_1 [as $do_ival] (/tmp/opal-nodejs-runner-20151031-75-refeve:18884:18)
    at Opal.dynamic_require_severity (/tmp/opal-nodejs-runner-20151031-75-refeve:18896:64)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20151031-75-refeve:18897:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

root@default:/host/opal# ruby ../bah.rb 
about to call block 1
block 1
about to call block foo
block 2
```

**Comment by wied03** [comment]
```js
 klass = ($a = ($b = $scope.get('Class')).$new, $a.$$p = (TMP_2 = function(){var self = TMP_2.$$s || this;

  self.$puts("hello?");
    return (Opal.def(self, '$hi', function() {
      var self = this;

      return self.$puts("hi");
    }), nil) && 'hi';}, TMP_2.$$s = self, TMP_2), $a).call($b, self.$base_klass());
```

local var version:
```js
bk = self.$base_klass();
  klass = ($a = ($b = $scope.get('Class')).$new, $a.$$p = (TMP_2 = function(){var self = TMP_2.$$s || this;

  self.$puts("hello?");
    return (Opal.def(self, '$hi', function() {
      var self = this;

      return self.$puts("hi");
    }), nil) && 'hi';}, TMP_2.$$s = self, TMP_2), $a).call($b, bk);
```

**Comment by wied03** [comment]
@jgaskins - Can your keen JS eyes pick up what's going on here? It kind of has me stumped. I'm guessing the problem has to do with a property placed on the `bk` local variable which causes this to work and that doesn't exist when the method call is passed directly in.

**Comment by jgaskins** [comment]
@wied03 It doesn't look like there should be anything different, but I'll have a closer look when I get home tonight.

**Comment by jgaskins** [comment]
Indeed, according to Safari's profiler, it's never executed (denoted by low opacity).

<img width="626" alt="screen shot 2015-10-29 at 9 14 11 pm" src="https://cloud.githubusercontent.com/assets/108205/10836283/232935c8-7e82-11e5-9b92-e56192aed209.png">

**Comment by jgaskins** [comment]
I copy/pasted the compiled code into the JS console just to see if maybe I was just overlooking some difference between the two. It works if you pass a variable, but not if you use the return value of the method.

Even more bizarre, it doesn't work if you use inline assignment:

```ruby
klass = (all_that_stuff).call($d, bk = self.$base_klass());
```

**Comment by wied03** [comment]
It actually has nothing to do with classes, updated.

**Comment by meh** [comment]
Oh man, this is going to be a pain to fix.

**Comment by wied03** [comment]
Yep. Didn't even attempt a PR on that one. :/

sent from my mobile device

**Comment by meh** [comment]
I think I know how to fix it, working on it.
