### ISSUE TITLE
Getting error NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by watzon** [opal/opal#1192]
I'm getting the error while trying to precompile assets in rails. The stack trace is as follows: 

```
...
I, [2015-11-17T12:57:01.539098 #6877]  INFO -- : Writing /home/chris/Documents/Projects/rcredit/public/assets/stringio-0947edf468ff78f165a0241faeeb5af352c76e10b54977a383ae3a01b1778091.js
I, [2015-11-17T12:57:01.542145 #6877]  INFO -- : Writing /home/chris/Documents/Projects/rcredit/public/assets/strscan-647d5cb41223405ff674f0264b0497be2b3f25d0671e46825805798d3ed35733.js
I, [2015-11-17T12:57:01.545573 #6877]  INFO -- : Writing /home/chris/Documents/Projects/rcredit/public/assets/template-9bdeaa93cd74f7de56189ecdc036ba01ab84835d7438abbef86bf39d328266d3.js
I, [2015-11-17T12:57:01.577079 #6877]  INFO -- : Writing /home/chris/Documents/Projects/rcredit/public/assets/thread-9d1b3bfd1b4d751a93e00cf31cad071c97942b6d86c6502da61f856803fd6ca6.js
I, [2015-11-17T12:57:01.589836 #6877]  INFO -- : Writing /home/chris/Documents/Projects/rcredit/public/assets/time-d537c83f9d178b8af4f2a61ba696c39229971e8667eb6f82bac4f5da54dc5f05.js
I, [2015-11-17T12:57:01.600990 #6877]  INFO -- : Writing /home/chris/Documents/Projects/rcredit/public/assets/yaml-adc2fa1e3f914bd1d87798f04faf383208c6e4b851b72cf0320e7d64e39095b6.js
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/home/chris/.rvm/gems/ruby-2.2.2/gems/opal-0.8.1/lib/mspec/opal/main.rb.erb:4:in `_evaluate_template'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/erb_processor.rb:26:in `call'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/erb_processor.rb:13:in `call'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:60:in `block in load'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:44:in `load'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `yield'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `load'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/bundle.rb:23:in `block in call'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/utils.rb:183:in `dfs'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/bundle.rb:24:in `call'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:60:in `block in load'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/loader.rb:44:in `load'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `yield'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `load'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/base.rb:66:in `find_asset'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/manifest.rb:138:in `block in find'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:204:in `each'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:226:in `block in stat_tree'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:204:in `each'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:226:in `block in stat_tree'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:204:in `each'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/legacy.rb:105:in `each'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/legacy.rb:104:in `each'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/manifest.rb:136:in `find'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/sprockets/manifest.rb:162:in `compile'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-3.4.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/chris/.rvm/gems/ruby-2.2.2/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/chris/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/chris/.rvm/rubies/ruby-2.2.2/bin/rake:33:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by elia** [comment]
Looks like you're requiring "mspec/opal/main" which is meant to be used only to run rubyspec. Is that intentional?

(Anyway I'll make sure it won't be in the default paths in the next release)
