### ISSUE TITLE
Passing block explicitly to superclass method fails

### ISSUE THREAD

**Issue by wied03** [opal/opal#1237]
At one point this worked (or maybe was not fully working) in Opal 0.9 but now it complains:

```ruby
class SuperClass
  def add_stub(&block)
    puts 'super method, calling block'
    block.call
  end
end

class InheritingClass < SuperClass
  def add_stub(*args, &block)
    super(*args, &block)
  end
end

InheritingClass.new.add_stub do
  puts 'block ran'
end
```

Runs OK in MRI. It does not happen with a standalone method nor does it happen when 1 method calls another in the same fashion, just when calling the superclass' method. This also causes arity checking to break.

MRI:
```
super method, calling block
block ran
```

Opal:
```
super method, calling block

/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:4249
      throw exception;
            ^
call: undefined method `call' for nil
    at OpalClass.Opal.defs.self [as $new] (/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:4466:15)
    at NilClass.Opal.defn.TMP_1 (/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:3028:54)
    at NilClass.method_missing_stub [as $call] (/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:888:35)
    at $InheritingClass.Opal.defn.TMP_1 (/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:19037:20)
    at $InheritingClass.Opal.defn.TMP_2 [as $add_stub] (/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:19056:72)
    at Opal.dynamic_require_severity (/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:19061:66)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20151209-19233-13hhbbd:19062:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by elia** [comment]
the number `-4` is right (confirmed on cruby) so the problem must reside in the check:

https://github.com/opal/opal/blob/3d5f8d32a75f56d8a5d36e298060dad6db7c5be3/lib/opal/nodes/def.rb#L238-L267

**Comment by wied03** [comment]
Looks like in the superclass case, the block isn't in `TMP_1.$$p`, it's in `arguments`, which causes arguments to be 5 instead of the 4 it's expecting

**Comment by wied03** [comment]
In a way, this has nothing to do with arity checking. If I disable arity checking, then the code fails because  `implementation` is nil

**Comment by elia** [comment]
So it's more like the arity check message can be improved…

**Comment by wied03** [comment]
Maybe. The bigger problem is the block thing. This reminds me of https://github.com/opal/opal/pull/1132.
