### ISSUE TITLE
Cannot parse %<hello>

### ISSUE THREAD

**Issue by vais** [opal/opal#1242]
```
$ bundle exec opal -ve "%<hello>"
Opal v0.9.0.rc1
/vagrant/opal/lib/opal/parser/lexer.rb:513:in `add_string_content': An error occurred while compiling: -e (RuntimeError)

reached EOF while in string
Source: -e:1:8
%<hello>
~~~~~~~^
	from /vagrant/opal/lib/opal/parser/lexer.rb:412:in `parse_string'
	from /vagrant/opal/lib/opal/parser/lexer.rb:646:in `yylex'
	from /vagrant/opal/lib/opal/parser/lexer.rb:84:in `next_token'
	from /vagrant/opal/lib/opal/parser.rb:61:in `next_token'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/racc-1.4.13/lib/racc/parser.rb:271:in `_racc_do_parse_c'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/racc-1.4.13/lib/racc/parser.rb:271:in `do_parse'
	from /vagrant/opal/lib/opal/parser.rb:54:in `parse_to_sexp'
	from /vagrant/opal/lib/opal/parser.rb:39:in `parse'
	from /vagrant/opal/lib/opal/compiler.rb:149:in `compile'
	from /vagrant/opal/lib/opal/builder_processors.rb:91:in `compiled'
	from /vagrant/opal/lib/opal/builder_processors.rb:101:in `requires'
	from /vagrant/opal/lib/opal/builder.rb:41:in `build_str'
	from /vagrant/opal/lib/opal/cli.rb:110:in `block in build'
	from /vagrant/opal/lib/opal/cli.rb:154:in `evals_or_file'
	from /vagrant/opal/lib/opal/cli.rb:109:in `build'
	from /vagrant/opal/lib/opal/cli.rb:119:in `compiled_source'
	from /vagrant/opal/lib/opal/cli.rb:85:in `run_code'
	from /vagrant/opal/lib/opal/cli.rb:69:in `run'
	from /vagrant/opal/bin/opal:22:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/opal:23:in `load'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/opal:23:in `<main>'
```
Cannot pull any more updates from RubySpec until this is fixed (either in the Opal parser or changed in RubySpec)

**Comment by alexdowad** [comment]
Fixed in 87c8b66.
