### ISSUE TITLE
Unable to parse Unicode constants

### ISSUE THREAD

**Issue by vais** [opal/opal#1312]
Blocks Opal from being able to run `rubyspec/core/module/const_defined_spec.rb`
```
$ bundle exec rake mspec_rubyspec_nodejs PATTERN=spec/rubyspec/core/module/const_defined_spec

...

/Users/vais/opal/lib/opal/parser/lexer.rb:1258:in `yylex': An error occurred while compiling: rubyspec/core/module/fixtures/constant_unicode (RuntimeError)

Unexpected content in parsing stream `λ = ` :rubyspec/core/module/fixtures/constant_unicode:4
Source: rubyspec/core/module/fixtures/constant_unicode:4:10
  CS_CONSTλ = :const_unicode
~~~~~~~~~^
	from /Users/vais/opal/lib/opal/parser/lexer.rb:84:in `next_token'
	from /Users/vais/opal/lib/opal/parser.rb:61:in `next_token'
	from /Users/vais/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /Users/vais/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
	from /Users/vais/opal/lib/opal/parser.rb:54:in `parse_to_sexp'
	from /Users/vais/opal/lib/opal/parser.rb:39:in `parse'
	from /Users/vais/opal/lib/opal/compiler.rb:149:in `compile'
	from /Users/vais/opal/lib/opal/builder_processors.rb:91:in `compiled'
	from /Users/vais/opal/lib/opal/builder_processors.rb:101:in `requires'
	from /Users/vais/opal/lib/opal/builder.rb:139:in `process_require'
	from /Users/vais/opal/lib/opal/builder.rb:144:in `block in process_requires'
	from /Users/vais/opal/lib/opal/builder.rb:144:in `map'
	from /Users/vais/opal/lib/opal/builder.rb:144:in `process_requires'
	from /Users/vais/opal/lib/opal/builder.rb:139:in `process_require'
	from /Users/vais/opal/lib/opal/builder.rb:42:in `block in build_str'
	from /Users/vais/opal/lib/opal/builder.rb:42:in `map'
	from /Users/vais/opal/lib/opal/builder.rb:42:in `build_str'
	from /Users/vais/opal/lib/opal/cli.rb:111:in `block in build'
	from /Users/vais/opal/lib/opal/cli.rb:159:in `evals_or_file'
	from /Users/vais/opal/lib/opal/cli.rb:110:in `build'
	from /Users/vais/opal/lib/opal/cli.rb:121:in `compiled_source'
	from /Users/vais/opal/lib/opal/cli.rb:85:in `run_code'
	from /Users/vais/opal/lib/opal/cli.rb:71:in `run'
	from bin/opal:22:in `<main>'
```

**Comment by iliabylich** [comment]
I know it sounds weird, but what do you think about using the following regexp?
``` ruby
/[A-Z][^\u0001-\u002F\u003A-\u0040\u005B-\u005E\u0060\u007B-\u007F]+/
```

I'm pretty sure this regexp covers all possible constant names and it's platform-independent, works in both Ruby and JS.

Does anyone have any other ideas how to solve this? There are too many unicode characters that are not allowed to be used in a constant name.
