### ISSUE TITLE
Incorrect type with splat operator in HikePathFinder with Opal.paths

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1331]
As you may know, I'm trying to compile Ruby to JavaScript in JavaScript #1292 
I'm making progress but I hit the following error:
```
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:471:13)
    at join [as $join] (/home/guillaume/workspace/opensource/asciidoctor.js/npm/nodejs.js:143:28)
    at $Pathname.$+ (/home/guillaume/workspace/opensource/asciidoctor.js/npm/pathname.js:109:61)
    at $rb_plus (/home/guillaume/workspace/opensource/asciidoctor.js/npm/pathname.js:6:90)
    at $a.$$p.TMP_1 (/home/guillaume/workspace/opensource/asciidoctor.js/npm/pathname.js:138:18)
    at Opal.yield1 (/home/guillaume/workspace/opensource/asciidoctor.js/node_modules/opal-npm-wrapper/opal.js:1102:14)
    at Array.each [as $each] (/home/guillaume/workspace/opensource/asciidoctor.js/node_modules/opal-npm-wrapper/opal.js:10718:26)
    at Array.reverse_each [as $reverse_each] (/home/guillaume/workspace/opensource/asciidoctor.js/node_modules/opal-npm-wrapper/opal.js:11538:74)
    at $Pathname.join [as $join] (/home/guillaume/workspace/opensource/asciidoctor.js/npm/pathname.js:143:44)
    at $Paths.normalize_element [as $normalize_element] (/home/guillaume/workspace/opensource/asciidoctor.js/npm/opal-builder.js:601:28)
```

I followed the trace back to this line: https://github.com/opal/opal/blob/master/lib/opal/hike_path_finder.rb#L8

The method `append_paths` takes a `paths` argument. In this case the argument equals `Opal.paths`.
As far as I know the star symbol is the splat operator. It expands an Array into a list of arguments.
So I believe we have an Array of Strings and the splat operator transforms this array into a list of String arguments.

We then call:

 1. `Opal::HikePathFinder.append_paths(*paths)`: https://github.com/opal/opal/blob/master/lib/opal/hike_path_finder.rb#L8
 2. `Hike::Trail.append_paths(*path)`: https://github.com/sstephenson/hike/blob/v1.2.3/lib/hike/trail.rb#L67
 3. `Hike::NormalizedArray.push(*elements)`: https://github.com/sstephenson/hike/blob/v1.2.3/lib/hike/normalized_array.rb#L41
 4. `Hike::Paths.normalize_element(path)`: https://github.com/sstephenson/hike/blob/v1.2.3/lib/hike/paths.rb#L21

I added a `console.log('path', path);` in `Hike::Paths.normalize_element(path)` method:
`path { '$$id': 668, path: [String: 'opal'] }`

As you can see `path` is not a String hence the error.

**Comment by wied03** [comment]
We're working on similar things here - https://github.com/cj/opal-webpack/issues/12

**Comment by Mogztter** [comment]
@wied03 cool let me know if you find a solution :+1:

**Comment by wied03** [comment]
@Mogztter - Have you tried again recently? I'm able to compile a lot of stuff from JS now and I haven't seen this error. I did have to submit several PRs for File.extname, basename, and some Pathname methods to get there though (and I monkey patched using your Pathname#entries code). Still some other work that needs to be submitted as Opal PRs as well (dependent on that FileUtils testing discussion)

**Comment by Mogztter** [comment]
@wied03 I think you're right, I've successfully compiled Asciidoctor to JavaScript!
