### ISSUE TITLE
undefined method `read' for #<File> in PathReader

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1332]
The following error is thrown when executing [this line](https://github.com/opal/opal/blob/master/lib/opal/path_reader.rb#L12) in a Node.js environment: 

```
undefined method `read' for #<File:0x2b8>
    at null.$new (/home/guillaume/workspace/opensource/asciidoctor.js/node_modules/opal-npm-wrapper/opal.js:4581:15)
    at $File.method_missing [as $method_missing] (/home/guillaume/workspace/opensource/asciidoctor.js/node_modules/opal-npm-wrapper/opal.js:3132:54)
    at $File.method_missing_stub [as $read] (/home/guillaume/workspace/opensource/asciidoctor.js/node_modules/opal-npm-wrapper/opal.js:970:35)
    at $a.$$p.TMP_1 (/home/guillaume/workspace/opensource/asciidoctor.js/npm/opal-builder.js:903:18)
    at Opal.yield1 (/home/guillaume/workspace/opensource/asciidoctor.js/node_modules/opal-npm-wrapper/opal.js:1102:14)
    at open [as $open] (/home/guillaume/workspace/opensource/asciidoctor.js/npm/nodejs.js:187:21)
    at $PathReader.read [as $read] (/home/guillaume/workspace/opensource/asciidoctor.js/npm/opal-builder.js:903:58)
    at $Builder.read [as $read] (/home/guillaume/workspace/opensource/asciidoctor.js/npm/opal-builder.js:14194:44)
    at $Builder.build [as $build] (/home/guillaume/workspace/opensource/asciidoctor.js/npm/opal-builder.js:14064:23)
```

The method `File.read(path)` is [defined](https://github.com/opal/opal/blob/master/stdlib/nodejs/file.rb#L10) but here we are reading the input stream ? How can we define this method ?

Thanks

**Comment by wied03** [comment]
@Mogztter - this is fixed now, right?

**Comment by Mogztter** [comment]
@wied03 No method `read` without argument doesn't exist yet, this will be fixed when https://github.com/opal/opal/pull/1348 is merged.
