### ISSUE TITLE
undefined method `unpack'

### ISSUE THREAD

**Issue by loretoparisi** [opal/opal#1413]
Given

``` ruby
@char = "中"
puts @char.unpack("U")
```

I get compiled javascript

``` javascript
/* Generated by Opal 0.9.0 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;
  if (self["char"] == null) self["char"] = nil;

  Opal.add_stubs(['$puts', '$unpack']);
  self["char"] = "中";
  return self.$puts(self["char"].$unpack("U"));
})(Opal);
```

and then

``` shell
unpack: undefined method `unpack' for "中":String
unpack: undefined method `unpack' for "中":String
    at $.$new (http://opalrb.org/javascripts/try.js:6:8830)
    at String.Opal.defn.TMP_5 (http://opalrb.org/javascripts/try.js:5:20896)
    at String.n [as $unpack] (http://opalrb.org/javascripts/try.js:4:24433)
    at eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:24:19155), <anonymous>:10:34)
    at eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:24:19155), <anonymous>:11:3)
    at $TryOpal.$eval_code (http://opalrb.org/javascripts/try.js:24:19150)
    at $TryOpal.$run_code (http://opalrb.org/javascripts/try.js:24:18969)
    at e.$$p.$ (http://opalrb.org/javascripts/try.js:24:18266)
    at HTMLAnchorElement.a (http://opalrb.org/javascripts/try.js:23:24916)
    at HTMLAnchorElement.K.event.dispatch (http://opalrb.org/javascripts/application.js:3:4968)
```

**Comment by elia** [comment]
@loretoparisi yes, `Array#pack` and `String#unpack` are not yet implemented.

I'll leave this issue open and offer help to anyone who wants to try implement one of those methods :)

**Comment by Mogztter** [comment]
@loretoparisi Should be OK now: https://github.com/opal/opal/pull/1723

And I'm working on `Array#pack('U')`: https://github.com/opal/opal/pull/1731

**Comment by loretoparisi** [comment]
Thanks closing that.
