### ISSUE TITLE
Can't require openssl?

### ISSUE THREAD

**Issue by NullVoxPopuli** [opal/opal#1470]
So, I'm new to opal. I'd eventually like to build a GUI for my app in Electron, so I'm experimenting with different ways to do that. First I'm trying to convert my gem into JS, since Electron is node-based.

here are my files:
```ruby
# Rakefile
# frozen_string_literal: true
require 'bundler/gem_tasks'

require 'opal'

desc "Build our app to meshchat.js"
task :build do
  Opal.append_path '/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/meshchat-0.10.2/lib/'
  Opal.append_path '/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/'
  Opal.append_path './lib/'

  File.binwrite "meshchat.js", Opal::Builder.build("./run.rb").to_s
end

```

```ruby
# run.rb
require 'meshchat'

Meshchat.start(
  name: 'Spiced Rumby',
  version: '0.10.1',
  display: Meshchat::Ui::Display::ReadlineDisplay, # your class implementing `Display::Base`
  input: Meshchat::Ui::CLI::ReadlineInput
)

```

and my error: 

```bash
webdev@ubuntu 192.168.163.129  ~/Development/meshchat
⬡ v5.10.1 💎  2.3.0@meshchat (master) $ rake build
meshchat 0.10.2 built to pkg/meshchat-0.10.2.gem.
rake aborted!
Opal::Builder::MissingRequire: A file required by "./run.rb" wasn't found.
A file required by "meshchat" wasn't found.
can't find file: "openssl" in ["/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/opal", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/stdlib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/meshchat-0.10.2/lib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems", "/home/webdev/Development/meshchat/lib"]
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:118:in `read'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:127:in `process_require'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `block in process_requires'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `map'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `process_requires'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:139:in `process_require'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `block in build_str'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `map'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `build_str'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:35:in `build'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:30:in `build'
/home/webdev/Development/meshchat/Rakefile:12:in `block in <top (required)>'
Opal::Builder::MissingRequire: A file required by "meshchat" wasn't found.
can't find file: "openssl" in ["/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/opal", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/stdlib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/meshchat-0.10.2/lib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems", "/home/webdev/Development/meshchat/lib"]
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:118:in `read'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:127:in `process_require'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `block in process_requires'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `map'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `process_requires'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:139:in `process_require'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `block in build_str'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `map'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `build_str'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:35:in `build'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:30:in `build'
/home/webdev/Development/meshchat/Rakefile:12:in `block in <top (required)>'
Opal::Builder::MissingRequire: can't find file: "openssl" in ["/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/opal", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/stdlib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/meshchat-0.10.2/lib", "/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems", "/home/webdev/Development/meshchat/lib"]
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:118:in `read'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:127:in `process_require'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `block in process_requires'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `map'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:144:in `process_requires'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:139:in `process_require'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `block in build_str'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `map'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:42:in `build_str'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:35:in `build'
/home/webdev/.rvm/gems/ruby-2.3.0@meshchat/gems/opal-0.9.2/lib/opal/builder.rb:30:in `build'
/home/webdev/Development/meshchat/Rakefile:12:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)

```

openssl is a corelib, right? odes opal support core libs?

**Comment by wied03** [comment]
openssl is a C library. Opal on the browser can't support that. With Opal on Node, there has not been any work yet to try and implement this.
