### ISSUE TITLE
Subclassing Module does not allow overriding initializer

### ISSUE THREAD

**Issue by wied03** [opal/opal#1476]
test code:

```ruby
class Foobar < Module
  def initialize(description)
    @description = description
  end

  def inspect
    "#<#{self.class.name} #{@description.inspect}>"
  end

  alias to_s inspect
end

ModTest = Foobar.new('the mod')
puts ModTest

class Bar
  include ModTest
end
```

```ruby test.rb```:
```
#<Foobar "the mod">
```
```bundle exec opal -A test.rb```: (opal version a636e47a0cc8728c5b5fe67303a0ba14ae300542)
```
/tmp/opal-nodejs-runner-20160602-1520-av8wcu:1035
    throw Opal.ArgumentError.$new('[' + inspect + '] wrong number of arguments
                             ^
ArgumentError: [.initialize] wrong number of arguments(1 for 0)
    at Opal.defs.TMP_1 [as $new] (/tmp/opal-nodejs-runner-20160602-1520-av8wcu:4985:15)
    at Opal.ac (/tmp/opal-nodejs-runner-20160602-1520-av8wcu:1035:30)
    at module_constructor.ːinitialize (/tmp/opal-nodejs-runner-20160602-1520-av8wcu:2295:63)
    at Opal.defn.TMP_4 [as $new] (/tmp/opal-nodejs-runner-20160602-1520-av8wcu:3199:23)
    at self (/tmp/opal-nodejs-runner-20160602-1520-av8wcu:20729:54)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20160602-1520-av8wcu:20739:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

We fail the arity check because `Module#initialize` is running and not the overridden initializer.

**Comment by elia** [comment]
I'm quite sure the problem comes from using `Module#allocate` which doesn't take into account the fact that it's being called from a module subclass:

https://github.com/opal/opal/blob/master/opal/corelib/module.rb#L2-L10

Need to dig deeper to find a solution.
