### ISSUE TITLE
Test took forever

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1488]
I started the rake and it ran forever, maybe waiting on stdin, and finally I hit ctrl C after I came home. 

```
mdupont@mdupont-Aspire-7750G:~/experiments/opal$ rake
/usr/bin/ruby2.3 /usr/bin/rspec --pattern spec/lib/\*\*/\*_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 6078
..................................................................................this method is deprecated from the public API
................................
^C
RSpec is shutting down and will print the summary report... Interrupt again to force quit.
rake aborted!
Interrupt: 

Tasks: TOP => default => rspec
(See full trace by running task with --trace)
mdupont@mdupont-Aspire-7750G:~/experiments/opal$ F

Failures:

  1) Opal::CliRunners::Phantomjs sets env
     Failure/Error:
       expect(output_of(%{
         var ENV = JSON.parse(callPhantom(['env']));
         callPhantom(['stdout', JSON.stringify(ENV)]);
         callPhantom(['exit', 0]);
       }, [])).to include(%{"FOO":"BAR"})

       expected "Unable to open file '/dev/stdin'\n\n  phantomjs://platform/fs.js:79 in open\n  phantomjs://platform/fs.js:110 in read\n" to include "\"FOO\":\"BAR\""
       Diff:
       @@ -1,2 +1,5 @@
       -"FOO":"BAR"
       +Unable to open file '/dev/stdin'
       +
       +  phantomjs://platform/fs.js:79 in open
       +  phantomjs://platform/fs.js:110 in read

     # ./spec/lib/cli_runners/phantomjs_spec.rb:20:in `block (2 levels) in <top (required)>'

Deprecation Warnings:

RSpec::Core::Configuration#treat_symbols_as_metadata_keys_with_true_values= is deprecated, it is now set to true as default and setting it to false has no effect.

Using `should_not_receive` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /home/mdupont/experiments/opal/spec/lib/sprockets/processor_spec.rb:54:in `block (3 levels) in <top (required)>'.

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /home/mdupont/experiments/opal/spec/lib/sprockets/processor_spec.rb:65:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

3 deprecation warnings total

Finished in 239 minutes 39 seconds (files took 0.42126 seconds to load)
115 examples, 1 failure

Failed examples:

rspec ./spec/lib/cli_runners/phantomjs_spec.rb:18 # Opal::CliRunners::Phantomjs sets env

Randomized with seed 6078

^C
mdupont@mdupont-Aspire-7750G:~/experiments/opal$ 

```

**Comment by elia** [comment]
> `       expected "Unable to open file '/dev/stdin'\n\n  phantomjs://platform/fs.js:79 in open\n  phantomjs://platform/fs.js:110 in read\n" to include "\"FOO\":\"BAR\""`

Looks like there's a problem with `/dec/stdin`, is that due to some particular distro? I never tried anything but OSX and Travis' linux

**Comment by h4ck3rm1k3** [comment]
you can get an account https://gcc.gnu.org/wiki/CompileFarm on the gnu compile farm and test on many different architectures. I have done changes to the requirements, which might have caused the problem

```
mdupont@mdupont-Aspire-7750G:~/experiments/opal$ git diff
diff --git a/opal.gemspec b/opal.gemspec
index a455de1..abd3567 100644
--- a/opal.gemspec
+++ b/opal.gemspec
@@ -22,7 +22,7 @@ Gem::Specification.new do |s|
 
   s.add_dependency 'sourcemap', '~> 0.1.0'
   s.add_dependency 'sprockets', '~> 3.1'
-  s.add_dependency 'hike', '~> 1.2'
+  s.add_dependency 'hike'
   s.add_dependency 'tilt', '>= 1.4'
   s.add_dependency 'ast', '>= 2.3.0'
   s.add_dependency 'parser', '>= 2.3.1.2'
@@ -30,11 +30,11 @@ Gem::Specification.new do |s|
   s.add_development_dependency 'mspec', '1.5.20'
   s.add_development_dependency 'rake'
   s.add_development_dependency 'racc'
-  s.add_development_dependency 'rspec', '~> 2.99'
-  s.add_development_dependency 'octokit', '~> 2.4.0'
+  s.add_development_dependency 'rspec'
+  s.add_development_dependency 'octokit'
   s.add_development_dependency 'bundler', '~> 1.5'
-  s.add_development_dependency 'yard', '~> 0.8.7'
+  s.add_development_dependency 'yard'
   s.add_development_dependency 'rack-test'
-  s.add_development_dependency 'opal-minitest'
+ # s.add_development_dependency 'opal-minitest'
   s.add_development_dependency 'coveralls'
 end

```

I will try and use your exact versions and try again.

**Comment by h4ck3rm1k3** [comment]
Ok reverted those changes and still get the hangs, here is one failing

    ruby -S rspec  --format d spec/lib/cli_runners/phantomjs_spec.rb:20 

Opal::CliRunners::Phantomjs sets env


This is the part that is hanging :

    /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs /home/mdupont/experiments/opal/lib/opal/cli_runners/phantom.js

It seems to be the problem with pipes. 
it looks like you are trying to read something, but that is not working.
     var opal_code = fs.read('/dev/stdin');

**Comment by h4ck3rm1k3** [comment]
THIS IS MY WORKAROUND 

    rm spec/lib/cli_runners/phantomjs_spec.rb

**Comment by Mogztter** [comment]
@h4ck3rm1k3 This is a bug in Phantom.js. Depending on the version of Phantom.js, I'm experiencing the same issue on Ubuntu 14.04 LTS

With the following version the build is working:
```
$ phantomjs -v
2.1.1
$ node -v
v0.12.0
```

**Comment by elia** [comment]
Thanks @h4ck3rm1k3 and @Mogztter for reporting and fixing this!

The windows build is now passing 😄  https://ci.appveyor.com/project/elia/opal/build/12
