### ISSUE TITLE
bad code generation when next is combined with assignment

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1492]
This code 
```
def test123?(command)
  command.dup.each_char do |c|
    env = false and  next if c !~ /[A-Za-z_]/
  end
end
```
Generates 
```
/* Generated by Opal 0.11.0.dev */
(function(Opal) {
  var TMP_2, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;
  Opal.add_stubs(['$each_char', '$!~', '$dup']);
  return (Opal.defn(Opal.Object, '$test123?', TMP_2 = function(command) {
    var $a, $b, TMP_1, self = this;
    return ($a = ($b = command.$dup()).$each_char, $a.$$p = (TMP_1 = function(c){var self = TMP_1.$$s || this, $c, env = nil;
if (c == null) c = nil;
    if ((($c = c['$!~'](/[A-Za-z_]/)) !== nil && $c != null && (!$c.$$is_boolean || $c == true))) {
        return ($c = (env = false), $c !== false && $c !== nil && $c != null ?return nil; : $c)
        } else {
        return nil
      }}, TMP_1.$$s = self, TMP_1.$$arity = 1, TMP_1), $a).call($b)
  }, TMP_2.$$arity = 1), nil) && 'test123?'
})(Opal);
```

This fails : 

```
/home/mdupont/experiments/httpd/libraries/test2.js:10
        return ($c = (env = false), $c !== false && $c !== nil && $c != null ?return nil; : $c)
                                                                                                                ^^^^^^
SyntaxError: Unexpected token return
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by elia** [comment]
Yeah, there's an issue with `next` combined with `and/or`. It's already tracked in #810, I'll add this alternate example there.

As a workaround, this should work:

```rb
def test123?(command)
  command.dup.each_char do |c|
    if c !~ /[A-Za-z_]/
      next if (env = false)
    end
  end
end
```
