### ISSUE TITLE
invalid multibyte escape:

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1509]
invalid multibyte escape: /[\x00-\x7F]|[\x80-\xBF][\xC0-\xF0]*|[\xC0-\xF0]/ (RegexpError)

I am not able to create an isolated test case yet, but I think it happens on this line :
https://github.com/rubysl/rubysl-rexml/blob/0ab7aae8d824606dc41e855445b1b993c25e9285/lib/rexml/text.rb#L142

```
/home/mdupont/experiments/opal/lib/opal/nodes/literal.rb:121:in `initialize': invalid multibyte escape: /[\x00-\x7F]|[\x80-\xBF][\xC0-\xF0]*|[\xC0-\xF0]/ (RegexpError)
	from /home/mdupont/experiments/opal/lib/opal/nodes/literal.rb:121:in `new'
	from /home/mdupont/experiments/opal/lib/opal/nodes/literal.rb:121:in `compile_static_regexp'
	from /home/mdupont/experiments/opal/lib/opal/nodes/literal.rb:100:in `compile'
	from /home/mdupont/experiments/opal/lib/opal/nodes/base.rb:190:in `compile_to_fragments'
	from /home/mdupont/experiments/opal/lib/opal/compiler.rb:310:in `process'
	from /home/mdupont/experiments/opal/lib/opal/nodes/base.rb:251:in `expr'
	from /home/mdupont/experiments/opal/lib/opal/nodes/arglist.rb:14:in `block in compile'
	from /home/mdupont/experiments/opal/lib/opal/nodes/arglist.rb:12:in `each'
	from /home/mdupont/experiments/opal/lib/opal/nodes/arglist.rb:12:in `compile'
```

**Comment by Mogztter** [comment]
I can reproduce this issue: `bundle exec opal -e "gsub(/[\x80-\xff]/n, '')"`

**Comment by iliabylich** [comment]
No, the issue here is that `\x80` is not a valid utf8 character. You can parse it by adding a `# encoding: ascii-8bit` comment to the beginning of your file. I don't know why MRI parses it.

**Comment by Mogztter** [comment]
Thanks @iliabylich for your input.

The code is from `ttfunk`: https://github.com/prawnpdf/ttfunk/blob/086b3126b13d207abf992279bef9b7699af8ae32/lib/ttfunk/table/name.rb#L20

I believe `\x80-\xFF` are non-ASCII character ranges: http://www.unicode.org/charts/PDF/U0080.pdf (C1 Controls and Latin-1 Supplement)

**Comment by iliabylich** [comment]
@Mogztter Yes, you are right. To parse this file you need to add an encoding comment.

**Comment by hmdne** [comment]
Related to #2235 - the 5aad139c7fcc92f4b5f7bd4412987843db535698 commit.
