### ISSUE TITLE
uninitialized constant Opal::UseGem::Gem when using opal-builder.js (master)

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1619]
```javascript
var Opal = require('opal-runtime').Opal;
var Builder = require('../src/index').Builder;

var builder = Builder.$new();
var result = builder.$build('spec/fixtures/hello.rb');
expect(result.$to_s()).toMatch(/self\.\$puts\("Hello world"\)/);
```

Source: https://github.com/Mogztter/opal-node-compiler

The following exception is thrown when running test `npm run test`:

```
> opal-compiler@0.11.0-integration1 test /home/guillaume/workspace/opensource/opal/opal-node-compiler
> node npm/test.js

Object freezing is not supported by Opal
Object tainting is not supported by Opal

/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:4873
      throw exception;
      ^
Gem: uninitialized constant Opal::UseGem::Gem
    at Opal.defs.TMP_Exception_new_1 [as $new] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:5101:15)
    at module_constructor.$$const_missing [as $const_missing] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:2896:75)
    at Opal.const_get (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:280:32)
    at module_constructor.$$require_paths_for_gem [as $require_paths_for_gem] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/src/opal-builder.js:26633:37)
    at module_constructor.$$use_gem [as $use_gem] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/src/opal-builder.js:26625:59)
    at module_constructor.Opal.defs.TMP_Opal_reset_paths$B_11 [as $reset_paths!] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/src/opal-builder.js:26661:12)
    at /home/guillaume/workspace/opensource/opal/opal-node-compiler/src/opal-builder.js:26665:26
    at Opal.modules.opal/paths (/home/guillaume/workspace/opensource/opal/opal-node-compiler/src/opal-builder.js:26666:5)
    at Opal.load (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:2215:7)
    at Object_alloc.Opal.require [as $require] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:2239:17)
```

**Comment by Mogztter** [comment]
```diff
-  # Resets Opal.paths to the default value (includes `corelib`, `stdlib`, `opal/lib`)
+  # Resets Opal.paths to the default value
+  # (includes `corelib`, `stdlib`, `opal/lib`, `ast` gem and `parser` gem)
   def self.reset_paths!
     @paths = [core_dir.untaint, std_dir.untaint, gem_dir.untaint]
+    use_gem 'ast'
+    use_gem 'parser'
     nil
   end
```

If I remove `use_gem 'ast'` and `use_gem 'parser'`, the next error is:

```
1) Opal node compiler When loaded builder should compile simple hello world
  Message:
    MissingRequire: can't find file: "spec/fixtures/hello.rb" in ["/home/guillaume/workspace/opensource/opal/opal-node-compiler/opal", "/home/guillaume/workspace/opensource/opal/opal-node-compiler/stdlib", "/home/guillaume/workspace/opensource/opal/opal-node-compiler"]
  Stack:
    MissingRequire: can't find file: "spec/fixtures/hello.rb" in ["/home/guillaume/workspace/opensource/opal/opal-node-compiler/opal", "/home/guillaume/workspace/opensource/opal/opal-node-compiler/stdlib", "/home/guillaume/workspace/opensource/opal/opal-node-compiler"]
        at Opal.defs.TMP_Exception_new_1 [as $new] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:5101:15)
        at Opal.send (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:1657:23)
        at $$exception [as $exception] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:5118:14)
        at $Builder.$$raise (/home/guillaume/workspace/opensource/opal/opal-node-compiler/node_modules/opal-runtime/src/opal.js:4858:31)
        at $Builder.$$read [as $read] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/src/opal-builder.js:26868:108)
        at $Builder.$$build [as $build] (/home/guillaume/workspace/opensource/opal/opal-node-compiler/src/opal-builder.js:26746:23)
        at Object.<anonymous> (/home/guillaume/workspace/opensource/opal/opal-node-compiler/spec/main.spec.js:17:28)
```

I should add a test case on Opal :flushed:

**Comment by Mogztter** [comment]
I think I found the root cause. I made a mistake here: https://github.com/opal/opal/blob/bdd75b3dd07c63a5ed232153e3bcc6c7b3722f89/stdlib/nodejs/file.rb#L86

The code should be:

```ruby
  def self.directory? path
    return nil unless exist? path
    `executeIOAction(function(){return !!__fs__.lstatSync(path).isDirectory()})`
  end
```

Otherwise the generated code is:

```javascript
    Opal.defs(self, '$directory?', TMP_File_directory$q_6 = function(path) {
      var $a, self = this;

      console.log(self['$exist?'](path));
      if ((($a = self['$exist?'](path)) !== nil && $a != null && (!$a.$$is_boolean || $a == true))) {
        } else {
        return nil
      };
      !!executeIOAction(function(){return __fs__.lstatSync(path).isDirectory()});
    }, TMP_File_directory$q_6.$$arity = 1);
```

Without `return` the function return `undefined`!

**Comment by Mogztter** [comment]
@elia I don't think `Opal::UseGem::Gem` is going to work in a JavaScript environment. Could we add a condition when running Opal in Opal ?

```ruby
def self.reset_paths!
  @paths = [core_dir.untaint, std_dir.untaint, gem_dir.untaint]
  if RUBY_ENGINE != 'opal'
    use_gem 'ast'
    use_gem 'parser'
  end
  nil
end
```
https://github.com/opal/opal/blob/bdd75b3dd07c63a5ed232153e3bcc6c7b3722f89/lib/opal/paths.rb#L73-L74
