### ISSUE TITLE
require_relative not working?

### ISSUE THREAD

**Issue by dan42** [opal/opal#1634]
When I do this
`require_relative "../app/helpers/lookup.rb"`    
I get the following error:
`Errno::ENOENT
No such file or directory @ rb_sysopen - /usr/domains/ANN/current/encyc/app/helpers/lookup`

This seems to be caused by Builder#process_require stripping the extension before doing `read(filename)` and then PathReader#expand not going through `file_finder.find` which would append the extension. I'm a bit lost as to why/how all this pathname munging is going on though.

**Comment by elia** [comment]
> I'm a bit lost as to why/how all this pathname munging is going on though.

It has mainly to do with how sprockets treats extensions and the fact that in the compiled code files are registered without extension.

Can you add some code or a CLI command to reproduce the error?

**Comment by wvengen** [comment]
I can reproduce this as follows:
```ruby
# test.rb
require_relative 'foo'
puts(foo)
```
```ruby
# foo.rb
def foo
  "this was foo"
end
```

Executing using ruby:

```sh
ruby test.rb
```
```
this was foo!
```

Executing using opal v1.0.5:
```sh
opal test.rb
```
```
Failed to load WithCLexer, using pure Ruby lexer
Traceback (most recent call last):
	12: from .../opal-1.0.5/bin/opal:4:in `<main>'
	11: from .../opal-1.0.5/bin/opal:4:in `load'
	10: from .../opal-1.0.5/exe/opal:24:in `<top (required)>'
	 9: from .../opal-1.0.5/lib/opal/cli.rb:67:in `run'
	 8: from .../opal-1.0.5/lib/opal/cli.rb:79:in `builder'
	 7: from .../opal-1.0.5/lib/opal/cli.rb:110:in `create_builder'
	 6: from .../opal-1.0.5/lib/opal/cli.rb:149:in `evals_or_file'
	 5: from .../opal-1.0.5/lib/opal/cli.rb:110:in `block in create_builder'
	 4: from .../opal-1.0.5/lib/opal/builder.rb:96:in `build_str'
	 3: from .../opal-1.0.5/lib/opal/builder.rb:96:in `map'
	 2: from .../opal-1.0.5/lib/opal/builder.rb:96:in `block in build_str'
	 1: from .../opal-1.0.5/lib/opal/builder.rb:196:in `process_require'
.../opal-1.0.5/lib/opal/builder.rb:182:in `read': can't find file: "foolib" in: (Opal::Builder::MissingRequire)
- .../opal-1.0.5/opal
- .../opal-1.0.5/stdlib
- .../opal-1.0.5/lib
- .../ast-2.4.1/lib
- .../ast-2.4.1/lib
- .../parser-2.7.2.0/lib
```

When adding an include path it works:
```sh
opal -I`pwd` test.rb
```
```
Failed to load WithCLexer, using pure Ruby lexer
this was foo!
```

This is very inconvenient, however, when there are many `require_relative` invocations in multiple directores.
