### ISSUE TITLE
WARNING: Cannot handle dynamic require -- tilt/mapping:243 When change opal directory name

### ISSUE THREAD

**Issue by zw963** [opal/opal#1649]
I want to package opal into my own ruby library toolkit.
(basically, some library which in $LOAD_PATH used by all version ruby.)

Following is directory structure:

```sh
 ╰─ $ tree -L 1
.
├── bin
├── bin.real
├── lib
├── opal1
└── stdlib
```

It failed with following error message:
```sh
 ╰─ $ 1  opal -e 'puts 100'
WARNING: Cannot handle dynamic require -- tilt/mapping:243
/home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:118:in `read': A file required by "opal" wasn't found. (Opal::Builder::MissingRequire)
A file required by "opal/sprockets" wasn't found.
A file required by "opal/sprockets/processor" wasn't found.
A file required by "tilt/opal" wasn't found.
A file required by "tilt" wasn't found.
A file required by "tilt/mapping" wasn't found.
can't find file: "monitor" in ["/home/zw963/Dropbox/common/ruby/opalrb/opal", "/home/zw963/Dropbox/common/ruby/opalrb/stdlib", "/home/zw963/Dropbox/common/ruby/opalrb/lib", "/home/zw963/Dropbox/common/ruby/opalrb/opal1", "/home/zw963/Dropbox/common/ruby/opalrb/stdlib"]
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:127:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:42:in `block in build_str'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:42:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:42:in `build_str'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:35:in `build'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:98:in `build'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:123:in `compiled_source'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:87:in `run_code'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:73:in `run'
	from /home/zw963/Dropbox/common/ruby/opalrb/bin/../bin.real/opal:24:in `<main>'
```

If I change `opal1` to `opal`, it worked.
```sh
 ╰─ $ tree -L 1
.
├── bin
├── bin.real
├── lib
├── opal
└── stdlib
```

```sh
 ╰─ $ opal -e 'puts 100'
100
```

**Comment by elia** [comment]
Although I'm failing to see the purpose of changing the dir name, I thinnk you can get past the error by adding the new path manually to the opal `LOAD_PATH`:

```
opal -Iopal1 -e 'puts 100'
```

Let me know if this is not sufficient to solve the problem

**Comment by zw963** [comment]
@elia, Thanks, I already do it as you expected.

But it not work, it must hard code that directory name to ``opal`` to make it work.

following is my bash scripts wrapper which run opal.

```sh
ROOT=$(dirname `readlink -e $0`)/..
ruby --disable-gems -I$ROOT/lib -ropal \
     $ROOT/bin.real/opal -I$ROOT/opal1 -I$ROOT/stdlib -ropal "$@"
```

Following is error message:

```sh
 ╰─ $ 1  opal -e 'puts 100'
WARNING: Cannot handle dynamic require -- tilt/mapping:243
/home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:118:in `read': A file required by "opal" wasn't found. (Opal::Builder::MissingRequire)
A file required by "opal/sprockets" wasn't found.
A file required by "opal/sprockets/processor" wasn't found.
A file required by "tilt/opal" wasn't found.
A file required by "tilt" wasn't found.
A file required by "tilt/mapping" wasn't found.
can't find file: "monitor" in ["/home/zw963/Dropbox/common/ruby/opalrb/opal", "/home/zw963/Dropbox/common/ruby/opalrb/stdlib", "/home/zw963/Dropbox/common/ruby/opalrb/lib", "/home/zw963/Dropbox/common/ruby/opalrb/opal1", "/home/zw963/Dropbox/common/ruby/opalrb/stdlib"]
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:127:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `block in process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:144:in `process_requires'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:139:in `process_require'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:42:in `block in build_str'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:42:in `map'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:42:in `build_str'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/builder.rb:35:in `build'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:98:in `build'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:123:in `compiled_source'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:87:in `run_code'
	from /home/zw963/Dropbox/common/ruby/opalrb/lib/opal/cli.rb:73:in `run'
	from /home/zw963/Dropbox/common/ruby/opalrb/bin/../bin.real/opal:24:in `<main>'
```

**Comment by zw963** [comment]
Though I think this maybe not  a bug ... it worked if change `opal1` to `opal` ...

Perhaps I should close this?

Thanks.
