### ISSUE TITLE
Unsupported sexp: or_asgn inside .JS block

### ISSUE THREAD

**Issue by elia** [opal/opal#1673]
reproducible with:

```
opal -cEO -e 'foo.JS.bar do; foo ||= bar; end'
⤑ opal -cEO -e 'foo.JS.bar do; foo ||= bar; end'
/Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/compiler.rb:344:in `process': Unsupported sexp: or_asgn (RuntimeError)
	from /Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/nodes/base.rb:107:in `expr'
	from /Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/nodes/logic.rb:247:in `compile'
	from /Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/nodes/base.rb:47:in `compile_to_fragments'
	from /Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/compiler.rb:342:in `process'
	from /Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/nodes/base.rb:115:in `stmt'
	from /Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/nodes/iter.rb:38:in `block in compile'
	from /Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.11.0.rc1/lib/opal/nodes/scope.rb:64:in `block in in_scope'
…
```

cc @iliabylich

**Comment by iliabylich** [comment]
`js_call`, `jsattr` and `jsattrasgn` nodes are not supported by `Opal::Rewriters::Base`, so rewriters do not visit children of these nodes. Should be a quick fix.

**Comment by elia** [comment]
Thanks! super fast fix! 😄
