### ISSUE TITLE
Use do end in config.ru not work.

### ISSUE THREAD

**Issue by zw963** [opal/opal#1685]
From a very simple example, expect to start a rack server use `rackup`.

```sh
├── Gemfile
├── Gemfile.lock
├── app
│   └── application.rb
├── config.ru
└── index.html
```

Following code is worked
```rb
require 'bundler'
Bundler.require

run Opal::Server.new {|s|
  s.append_path 'app'
  s.main = 'application'
end
}
```

But, if change to following, not worked

```rb
require 'bundler'
Bundler.require

run Opal::Server.new do |s|
  s.append_path 'app'
  s.main = 'application'
end
```

```sh
RuntimeError: Main asset path not configured (set 'main' within Opal::Server.new block)
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/opal-0.10.5/lib/opal/sprockets/server.rb:104:in `html'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/opal-0.10.5/lib/opal/sprockets/server.rb:92:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/opal-0.10.5/lib/opal/sprockets/server.rb:79:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/lint.rb:49:in `_call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
	/home/zw963/.rvm/gems/ruby-2.3.3@一个最简单的opal例子/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/home/zw963/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by zw963** [comment]
Sorry, my wrong. 

``run Opal::Server.new do |s|`` equals to ``run(Opal::Server.new) do |s|``

**Comment by zw963** [comment]
@elia , Still strange enough ...

Following is better?

```rb
Opal::Server.new {|s|
  s.append_path 'app'
  s.main = 'application'
end
}.start
```

**Comment by olistik** [comment]
FWIW I stumbled upon the same error, since I'm just more used to translate curly blocks into their do-end counterpart. 😅 

I wrapped the block with `()`:

```ruby
require 'opal-sprockets'

run (Opal::Server.new do |server|
  server.main = 'hello_world.js.rb'
  server.append_path 'app'
end)
```

but it could be better to provide a simpler example:

```ruby
require 'opal-sprockets'

app = Opal::Server.new do |server|
  server.main = 'hello_world.js.rb'
  server.append_path 'app'
end

run(app)
```

/cc @elia
