### ISSUE TITLE
Backtrace is cut too much when exception is raised directly from the Opal runtime

### ISSUE THREAD

**Issue by yhara** [opal/opal#1751]
When I use `Kernel#raise` to raise an exception, it has the full stacktrace.

```console
% cat a.rb
raise
% ./bin/opal a.rb

/private/var/folders/01/8_5tmzpj66z4fp1y27j2q9dw0000gn/T/opal-nodejs-runner-20180117-28622-b5paot:5038
      throw exception;
      ^
RuntimeError
    at /private/var/folders/01/8_5tmzpj66z4fp1y27j2q9dw0000gn/T/opal-nodejs-runner-20180117-28622-b5paot:21638:15
    at Object.<anonymous> (/private/var/folders/01/8_5tmzpj66z4fp1y27j2q9dw0000gn/T/opal-nodejs-runner-20180117-28622-b5paot:21639:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

However, some errors like NoMethodError has only one line of backtrace and we cannot know where they were born.

```
% cat a.rb
hello
% ./bin/opal a.rb

/private/var/folders/01/8_5tmzpj66z4fp1y27j2q9dw0000gn/T/opal-nodejs-runner-20180117-28603-1cf2rnr:5038
      throw exception;
      ^
hello: undefined method `hello' for main
```

This line looks like the cause (When the error is raised directly from the Opal runtime, `Kernel$raise` is not on the stack trace).
https://github.com/opal/opal/blob/ee50768d368959b33a77b58028a90ec9bded64a1/opal/corelib/error.rb#L17

**Comment by elia** [comment]
@yhara should be fixed by 319a384, let me know if you encounter any other edge case.
