### ISSUE TITLE
gsub with a Regexp overrides the global variables

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1961]
Consider the following code:

**test.rb**
```rb
FooBarRx = /^(foo)(bar)/
BarRx = /^(bar)/

def replace val
  p "replace #{val}"
  val.gsub BarRx do
    "a"
  end
end

def sub text
  if FooBarRx =~ text
    replace $1
    replace $2
  end
end

sub 'foobar'
```

#### MRI 
```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```
```
$ ruby test.rb
"replace foo"
"replace bar"
```
#### Opal
```
bundle exec opal test.rb
```
```
"replace foo"
"replace "

/tmp/opal-nodejs-runner-20190325-30674-7kqcte:4665
      throw exception;
      ^
gsub: undefined method `gsub' for nil
    at constructor.$$method_missing (/tmp/opal-nodejs-runner-20190325-30674-7kqcte:3907:56)
    at constructor.method_missing_stub (/tmp/opal-nodejs-runner-20190325-30674-7kqcte:1310:35)
    at Opal.send (/tmp/opal-nodejs-runner-20190325-30674-7kqcte:1671:19)
    at constructor.$$replace (/tmp/opal-nodejs-runner-20190325-30674-7kqcte:23342:12)
    at constructor.$$sub (/tmp/opal-nodejs-runner-20190325-30674-7kqcte:23353:19)
    at /tmp/opal-nodejs-runner-20190325-30674-7kqcte:23358:15
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20190325-30674-7kqcte:23359:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

Behind the scene Opal is calling `$gvars['~']` to resolve the match:

```js
self.$replace((($a = $gvars['~']) === nil ? nil : $a['$[]'](1))); // replace $1
```
```js
$a // {"$$id":66,"regexp":{},"begin":0,"string":"foobar","pre_match":"","post_match":"","matches":["foobar","foo","bar"]}
```

As you can see above, `$a` is correct.
Then `gsub` is executed, but now `$a` is `Opal.nil`:

```js
self.$replace((($a = $gvars['~']) === nil ? nil : $a['$[]'](2))); // replace $2
```
```js
$a // {"$$id":4}
```

It looks like the global variables for the current match are removed when gsub is called.

**Comment by Mogztter** [comment]
Confirmed: https://github.com/opal/opal/blob/a1f36da26a2da31770da3f0e24ea1ddd4fd4e7a1/opal/corelib/string.rb#L561
`gsub` will effectively replace the global variables :disappointed: 
It might be tricky to resolve this issue because we need to limit the "global" variables to the scope:


```rb
def replace
  'a'.gsub(/(a)/) do
    "b#{$1}"
  end
end

val = 'foobar'
if /^(foo)(bar)/ =~ val
  p $1
  p replace
  p $2
end
```

In Ruby, the output is:

```
"foo"
"ba"
"bar"
```

In Opal:

```
"foo"
"ba"
nil
```

**Comment by Mogztter** [comment]
As far as I understand the "global" variables are limited to the enclosing function:

```rb
def replace
  r = 'a'.gsub(/(a)/) do
    "b#{$1}" # "ba"
  end
  p $1 # "a"
  r
end

val = 'foobar'
if /^(foo)(bar)/ =~ val
  p $1 # "foo"
  p $2 # "bar"
  'b'.gsub(/(b)/, 'c')
  p $1 # $1 updated by gsub, now "b"
  p $2 # $2 updated by gsub, now nil
  p replace  # "ba"
  p $1 # $1 is still "b"
end

p $1 # $1 is still "b"
```

```
"foo"
"bar"
"b"
nil
"a"
"ba"
"b"
"b"
```

**Comment by mojavelinux** [comment]
I think the subject of this issue should be updated. These are not global variables. They are implicit local variables. The API documentation is very confusing because even it misuses the term global (as "special global variables"), but the following definition clarifies their scope:

> These global variables are thread-local and method-local variables.

From https://ruby-doc.org/core-2.6.2/Regexp.html#class-Regexp-label-Special+global+variables
