### ISSUE TITLE
Error Compiling under Node.js/Electron - consumer.computeColumnSpans is not a function

### ISSUE THREAD

**Issue by mistergibson** [opal/opal#2118]
I get this error when attempting to compile a resultant javascript file from Opal's compilation process. no matter how I enable/disable various requirements -- I get THIS same error repeatedly. 'consumer' appears to be an auto-generated reference during the Opal compilation process, so I'm bringing this to your attention. Please let me know if you have further questions or need more information to characterize the issue. Thanks

ERROR in ./src/main/gxg.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: /home/mistergibson/Documents/Development/gxg-studio/src/main/gxg.js: consumer.computeColumnSpans is not a function
        at buildMappingData (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/file/merge-map.js:146:12)
        at mergeSourceMap (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/file/merge-map.js:21:17)
        at generateCode (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/file/generate.js:74:39)
        at run (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/index.js:55:33)
        at run.next (<anonymous>)
        at Function.transform (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transform.js:27:41)
        at transform.next (<anonymous>)
        at step (/home/mistergibson/Documents/Development/gxg-studio/node_modules/gensync/index.js:254:32)
        at gen.next (/home/mistergibson/Documents/Development/gxg-studio/node_modules/gensync/index.js:266:13)
        at async.call.value (/home/mistergibson/Documents/Development/gxg-studio/node_modules/gensync/index.js:216:11)
     @ ./src/main/index.js 46:12-31
     @ multi ./src/main/index.js

**Comment by mistergibson** [comment]
Sorry.

This turned out to be a 'babel' issue, NOT an Opal issue: https://github.com/babel/babel-loader/issues/870

**Comment by mistergibson** [comment]
'consumer' does appear in the generated source code - I'm going to re-open this and see if it rings any bells with the developers.

**Comment by mistergibson** [comment]
SOLVED: by passing the resultant source code through minify it did *something* to the source code that allows it to compile flawlessly.

**Comment by mistergibson** [comment]
On second thought --> I think I should keep this open. Strictly speaking should it throw a compile error when un-minified? minify might cloak a deeper issue at play here. Your thoughts?

**Comment by hmdne** [comment]
This is a part of the source-map node module which you probably haven't included.
