### ISSUE TITLE
Compile fails when using `-P` option

### ISSUE THREAD

**Issue by JunichiIto** [opal/opal#2142]
I tried to compile without source map using `-P` option, but got error:

```
$ RUBYOPT="-ropal-jquery" be opal -P --compile app.rb > dist/app.js  
Failed to load WithCLexer, using pure Ruby lexer
bundler: failed to load command: opal (/Users/jnito/.rbenv/versions/2.7.2/bin/opal)
NoMethodError: undefined method `[]=' for nil:NilClass
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/opal-1.0.3/lib/opal/cli_options.rb:141:in `block in initialize'
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/2.7.0/optparse.rb:1621:in `block in parse_in_order'
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/2.7.0/optparse.rb:1575:in `catch'
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/2.7.0/optparse.rb:1575:in `parse_in_order'
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/2.7.0/optparse.rb:1569:in `order!'
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/2.7.0/optparse.rb:1666:in `permute!'
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/2.7.0/optparse.rb:1691:in `parse!'
  /Users/jnito/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/opal-1.0.3/exe/opal:8:in `<top (required)>'
  /Users/jnito/.rbenv/versions/2.7.2/bin/opal:23:in `load'
  /Users/jnito/.rbenv/versions/2.7.2/bin/opal:23:in `<top (required)>'
```

Maybe `options[:runner_options]` is `nil`?

https://github.com/opal/opal/blob/v1.0.3/lib/opal/cli_options.rb#L141

**Comment by elia** [comment]
Fixed in https://github.com/opal/opal/commit/321bc3edee5c85a43171e106de27a8f06906d86e, and released in v1.0.4
