### ISSUE TITLE
Bug:  Run `opal -Rchrome -e "puts 'Hello, Opal'"` failed.

### ISSUE THREAD

**Issue by zw963** [opal/opal#2275]
**Describe the bug**

Following command is describe in  https://github.com/opal/opal/blob/master/docs/headless_chrome.md
```
 ╰─ $ opal -Rchrome -e "puts 'Hello, Opal'"
Connecting to localhost:9222...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'source-map'
Require stack:
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/source-map-support.js
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/source-map-support.js:30:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/source-map-support.js',
    'internal/preload'
  ]
}
```
Opal version: …
1.2.0

Chrome version:  
Google Chrome 92.0.4515.131 on Arch linux.

----------------

Another issue is I have to run chrome server manually with:

```sh
$: google-chrome-stable --disable-gpu --headless --disable-web-security --remote-debugging-port=9222
```

Because it seem like opal 1.2.0 can't start chrome process automatically, it failed.

```sh
Connecting to localhost:9222...
/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/chrome.rb:117:in `spawn': No such file or directory - --headless (Errno::ENOENT)
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/chrome.rb:117:in `run_chrome_server'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/chrome.rb:103:in `with_chrome_server'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/chrome.rb:39:in `block in run'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/chrome.rb:166:in `mktmpdir'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/chrome.rb:38:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners/chrome.rb:18:in `call'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli_runners.rb:50:in `block in register_runner'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/lib/opal/cli.rb:63:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/opal-1.2.0/exe/opal:24:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal:23:in `load'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal:23:in `<main>'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by hmdne** [comment]
Is your /bin/sh by any chance symlinked to dash instead of bash? If yes, then can you run this:

```sh
[user@localhost is]# sh -c "command -v google-chrome-stable --headless"
/usr/bin/google-chrome-stable
[user@localhost is]# 
```

...and see if it returns the path to your Chromium executable? I believe this to be the culprit for the "another issue".

**Comment by hmdne** [comment]
Anyway I can reproduce the first issue... it happened a release ago.

**Comment by zw963** [comment]
> Is your /bin/sh by any chance symlinked to dash instead of bash? If yes, then can you run this:

No, i use arch linux, it not use dash (even, i never install dash, anyway)

```sh
sh -c "command -v google-chrome-stable --headless"
/usr/sbin/google-chrome-stable
```

**Comment by hmdne** [comment]
I think I found the issue. This line here, it's redundant and only works on git versions of Opal, which is why it wasn't caught:

https://github.com/opal/opal/blob/6a03ab014a828d58bd2b177b75925adfaeecc9dd/lib/opal/cli_runners/chrome.rb#L45

**Comment by hmdne** [comment]
This was fixed; but there's another issue with a Chrome runner to be fixed with #2339

**Comment by zw963** [comment]
Yes, first issue start working now.

```
 ╰─ $ opal -Rchrome -e "puts 'Hello, Opal'"
Connecting to localhost:9222...
Hello, Opal
```

**Comment by zw963** [comment]
But, still can't start chrome debug server automatially,

```
 ╰─ $ opal -Rchrome -e "puts 'Hello, Opal'"
Connecting to localhost:9222...
Connecting to localhost:9222...
sh: line 1: : command not found
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
```

 though, i don't think this is a issue,  in fact,  i prefer to start chrome server manually with:

$: google-chrome-stable --disable-gpu --headless --disable-web-security --remote-debugging-port=9222

so, if start chrome remote debug server if not too easy, maybe i can propose remove this feature.

**Comment by hmdne** [comment]
It totally works for me though. Do you test on hmdne/chrome-runner-touches branch?

**Comment by hmdne** [comment]
Also, if you test on this branch, you will need to call `bin/opal` not `opal`... or `bundle exec opal` in a directory where a Gemfile directs to the branch.

**Comment by zw963** [comment]
```
 ╰─ $ 1  bundle |grep opal
Using opal 1.3.0 from https://github.com/opal/opal (at hmdne/chrome-runner-touches@070e99b)
Using opal-browser 0.2.0 from https://github.com/opal/opal-browser
Using opal-sprockets 1.0.2
 ╰─ $ bundle exec opal -Rchrome -e "puts 'Hello, Opal'"
Connecting to localhost:9222...
Connecting to localhost:9222...
sh: line 1: : command not found
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Connecting to localhost:9222...
Failed to start chrome server
Make sure that you have it installed and that its version is > 59
 ╰─ $ google-chrome-stable --version
Google Chrome 92.0.4515.131 

```

**Comment by hmdne** [comment]
could you try running:

```
GOOGLE_CHROME_BINARY=google-chrome-stable bundle exec opal -Rchrome -e "puts 'Hello, Opal'"
```

**Comment by zw963** [comment]
> could you try running:
> 
> ```
> GOOGLE_CHROME_BINARY=google-chrome-stable bundle exec opal -Rchrome -e "puts 'Hello, Opal'"
> ```

it works, sorry for that, because some refactor in recent days, GOOGLE_CHROME_BINARY set to empty string ...

**Comment by zw963** [comment]
master branch is working too.

```
 ╰─ $ bundle exec opal -Rchrome -e "puts 'Hello, Opal'"
Connecting to localhost:9222...
Connecting to localhost:9222...

DevTools listening on ws://127.0.0.1:9222/devtools/browser/5aa860e1-a6a0-4823-bfe3-d8e39ba224bf
[1103/162703.196389:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for swiftshader
[1103/162703.196569:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
Connecting to localhost:9222...
Hello, Opal
```

Thank you very much!
