### ISSUE TITLE
Bug: opal-repl broken when require a not exists file.

### ISSUE THREAD

**Issue by zw963** [opal/opal#2298]
Please see backtrace.

```rb
╰─ $ opal-repl 
>> puts 'hello world'
hello world
=> nil
>> require 'hello'
/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:186:in `read': A file required by "(irb)" wasn't found. (Opal::Builder::MissingRequire)
can't find file: "hello" in:
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/opal
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/stdlib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/parser-3.0.2.0/lib

With the following extensions:
- .js
- .js.js
- .rb
- .js.rb
- .opal
- .js.opal
- .opalerb
- .js.opalerb
- .erb
- .js.erb

And the following processors:
- Opal::BuilderProcessors::JsProcessor
- Opal::BuilderProcessors::RubyProcessor
- Opal::BuilderProcessors::OpalERBProcessor
- Opal::BuilderProcessors::ERBProcessor
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:200:in `process_require'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:98:in `block in build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:98:in `map'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:98:in `build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:76:in `eval_ruby'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:56:in `run_line'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:65:in `run_input_loop'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:32:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/exe/opal-repl:5:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `load'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `<main>'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `<main>'
/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:186:in `read': can't find file: "hello" in: (Opal::Builder::MissingRequire)
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/opal
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/stdlib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/parser-3.0.2.0/lib

With the following extensions:
- .js
- .js.js
- .rb
- .js.rb
- .opal
- .js.opal
- .opalerb
- .js.opalerb
- .erb
- .js.erb

And the following processors:
- Opal::BuilderProcessors::JsProcessor
- Opal::BuilderProcessors::RubyProcessor
- Opal::BuilderProcessors::OpalERBProcessor
- Opal::BuilderProcessors::ERBProcessor
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:200:in `process_require'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:98:in `block in build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:98:in `map'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/builder.rb:98:in `build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:76:in `eval_ruby'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:56:in `run_line'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:65:in `run_input_loop'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/lib/opal/repl.rb:32:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-7c98c43f09b4/exe/opal-repl:5:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `load'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `<main>'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by hmdne** [comment]
Fixed by #2285
