### ISSUE TITLE
Bug: bConfig::CONFIG['host_os'] return ECMA-262 instead linux, which broken cli_runners/chrome.rb

### ISSUE THREAD

**Issue by zw963** [opal/opal#2311]
**Describe the bug**

The latest master.

**To Reproduce**

 ╰─ $ opal-repl
>> require 'rbconfig'
=> true
>> RbConfig::CONFIG['host_os']
=> "ECMA-262"

This broken following line

https://github.com/opal/opal/blob/master/lib/opal/cli_runners/chrome.rb#L143

which cause `chrome_executable` method return nil, so, when run following code:

```sh
 ╰─ $ opal -Rchrome -e "puts 'Hello, Opal'"
Connecting to localhost:9222...
""
/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners/chrome.rb:118:in `spawn': No such file or directory - --headless (Errno::ENOENT)
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners/chrome.rb:118:in `run_chrome_server'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners/chrome.rb:103:in `with_chrome_server'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners/chrome.rb:39:in `block in run'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners/chrome.rb:167:in `mktmpdir'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners/chrome.rb:38:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners/chrome.rb:18:in `call'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli_runners.rb:50:in `block in register_runner'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/lib/opal/cli.rb:65:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-6a03ab014a82/exe/opal:24:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal:23:in `load'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal:23:in `<main>'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by hmdne** [comment]
The problem is that corelib (ie. opal directory in the main repo) is only to be used by Opal, not runtime. Same goes with stdlib.

**Comment by hmdne** [comment]
Taking a closer look here: of course Opal would return something as a platform like "ECMA-262". You would need to test it in irb, not opal-repl.
