### ISSUE TITLE
Bug: Claiming a method expects 1 arg when in fact the method expects 2 args

### ISSUE THREAD

**Issue by AndyObtiva** [opal/opal#2390]
**Describe the bug**

Opal version: 1.4.1

While upgrading glimmer-dsl-opal to the latest Opal (1.4.1) and Rails (7.0.1), I encountered this odd issue multiple times.

![Screen Shot 2022-02-12 at 3 44 33 PM](https://user-images.githubusercontent.com/23052/153727831-c1e5a77c-0da4-4972-87dc-983baa3d05a1.png)

It is claiming that the method `handle_javascript_observation_request` is not expecting 2 args when in fact it definitely does as seen in the code below:

```ruby
      def handle_observation_request(keyword, original_event_listener)
        case keyword
        when 'on_widget_disposed'
          listeners_for(keyword.sub(/^on_/, '')) << original_event_listener.to_proc
        else
          handle_javascript_observation_request(keyword, original_event_listener)
        end
      end
      
      def handle_javascript_observation_request(keyword, original_event_listener)
        # ...
      end
```

One thing to note is that the 2nd argument is actually a Ruby proc. It seems every time I encountered this issue, it was with methods that take the last argument as a Ruby proc instead of accepting a Ruby `&block` as an optional block argument. Either way, it is fully legal in Ruby to supply the last argument as a Proc object instead of a `&block`, and this used to work in older Opal (1.1.1). So, I am not sure what is going on with the latest Opal 1.4.1

Another odd thing is that I added puts statements in the code and they showed that the code did work a few times before suddenly returning that error on a later invocation.

Sadly, the stack trace provided is not helpful at all for me as it does not mention Ruby classes (I remember Opal 1.1.1 giving better error messages; do I have something perhaps misconfigured in the new Opal?):
```ruby
"ArgumentError: `block in handle_javascript_observation_request': wrong number of arguments (given 2, expected 1)
    at Object.Opal.block_ac (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:1549:30)
    at $$95 (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:78125:42)
    at HTMLSelectElement.wrapper (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:70674:22)
    at HTMLSelectElement.dispatch (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:68630:43090)
    at HTMLSelectElement.v.handle (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:68630:41074)
    at Object.trigger (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:68630:71513)
    at HTMLSelectElement.<anonymous> (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:68630:72108)
    at Function.each (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:68630:2976)
    at S.fn.init.each (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:68630:1454)
    at S.fn.init.trigger (http://localhost:3000/assets/application-02f604bfbbc546c0f65e4914adab21cbaa4abe88c536ef3253c4f425410156f5.js:68630:72084)"
```

I tried modifying the method to take an extra 3rd argument that is optional `handle_javascript_observation_request(keyword, original_event_listener, extra = nil)`, and yet the error persisted in saying the method expects 1 arg only.

I even tried to clear the `tmp/cache` of the Rails 7 application and restarting the server, but that did not help.

**To Reproduce**

I cannot come up with a simple example outside of the glimmer-dsl-opal gem code that demonstrates this.

But, attached is the full Opal generated application.js file (zipped):

[application.js.zip](https://github.com/opal/opal/files/8054532/application.js.zip)

**Comment by AndyObtiva** [comment]
OK, it seems I misread the Opal error message. On closer inspection, I noticed it said "cause: constructor" and "block in handle_javascript_observation_request". Indeed, there is a Ruby block in the logic of "handle_javascript_observation_request" (which I did not share in the issue report). I'm looking into it now. If I resolve this issue, I'll just close it.

**Comment by elia** [comment]
👍 @AndyObtiva that's great! That happened to me many times too 😆 , the best kind of "errors"!
