### ISSUE TITLE
Not all default args semantics are supported.

### ISSUE THREAD

**Issue by meh** [opal/opal#384]
```
>> def has?(a = 42, b, c); [a, b, c]; end
parse error on value "," (",") ::1
        /home/meh/.gem/ruby/2.0.0/gems/opal-0.4.4/lib/opal/lexer.rb:40:in `on_error'
        /usr/lib/ruby/2.0.0/racc/parser.rb:258:in `_racc_do_parse_c'
        /usr/lib/ruby/2.0.0/racc/parser.rb:258:in `do_parse'
```

**Comment by elia** [comment]
fixed on master by @iliabylich
