### ISSUE TITLE
Class#clone is missing.

### ISSUE THREAD

**Issue by meh** [opal/opal#397]
I **really** need this in lissio.

**Comment by elia** [comment]
```rb
class A
  def self.class_method_name
    :asdf
  end
end

B = A.clone
p B.class_method_name
```

still incomplete:

```
opal:master ⤑ pbpaste | be bin/opal                                                                                                                                       ~/C/opal

/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4750-16pqjk0:4361
      throw exception;
      ^
class_method_name: undefined method `class_method_name' for B
    at null.$new (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4750-16pqjk0:4573:15)
    at ːmethod_missing (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4750-16pqjk0:3184:54)
    at method_missing_stub [as $class_method_name] (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4750-16pqjk0:993:35)
    at /private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4750-16pqjk0:18629:34
    at Object.<anonymous> (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4750-16pqjk0:18630:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
opal:master ⤑ pbpaste | ruby                                                                                                                                              ~/C/opal
:asdf
```

**Comment by dougo** [comment]
This works fine for me in 0.9.4... can this issue be closed?

**Comment by elia** [comment]
@dougo Nice catch, but sadly it's still broken on master :)

**Comment by iliabylich** [comment]
Fixed on master:
```
$ cat test.rb
class A
  def self.class_method_name
    :asdf
  end
end

B = A.clone
p B.class_method_name

$ opal test.rb
"asdf"
```
