### ISSUE TITLE
Bug with parameter less super inside a block with splat arguments

### ISSUE THREAD

**Issue by meh** [opal/opal#406]
This passes the wrong parameters:
```ruby
  %w([]= delete clear).each {|name|
    define_method name do |*args|
      super.tap {
        save if autosave?
      }
    end
  }
```

This works:
```ruby
  %w([]= delete clear).each {|name|
    define_method name do |*args|
      super(*args).tap {
        save if autosave?
      }
    end
  }
```

**Comment by wied03** [comment]
@meh - you can't do an implicit super from within `define_method` (Opal now checks for that). Can this be closed?

code:
```ruby
%w([]= delete clear).each {|name|
    define_method name do |*args|
      super.tap {
        save if autosave?
      }
    end
  }

clear 123
```
MRI 2.2.4:
```
junk.rb:3:in `block (2 levels) in <main>': implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly. (RuntimeError)
	from junk.rb:9:in `<main>'
```

**Comment by elia** [comment]
👍🏼
