### ISSUE TITLE
Issue with singleton class and method undefinition

### ISSUE THREAD

**Issue by meh** [opal/opal#469]
From RubySpec:

```ruby
      obj = mock('o')
      class << obj; undef :to_s; end
      lambda { [1, obj].send(@method) }.should raise_error(NoMethodError)
```

Ruby:
```ruby
>> a = Object.new
=> #<Object:0x0000000259fe78>
>> class << a; undef :to_s; end
=> nil
>> a.to_s
NoMethodError: undefined method `to_s' for #<Object:0x0000000259fe78>
    (ripl):3:in `<main>'
```

Opal:
```ruby
>> a = Object.new
=> #<Object:70>
>> class << a; undef :to_s; end
=> true
>> a.to_s
=> "#<Object:70>"
```

**Comment by elia** [comment]
Fixed on _master_

```rb
a = Object.new
class << a; undef :send; end
a.send 123
```

```
⤑ pbpaste | opal                                                                                                                                              ~/C/opal

/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160518-28384-wfe6i6:4554
      throw exception;
      ^
send: undefined method `send' for #<Object:0x10a>
    at Opal.defs.TMP_1 [as $new] (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160518-28384-wfe6i6:4781:15)
    at Object_alloc.ːmethod_missing (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160518-28384-wfe6i6:3337:54)
    at Object_alloc.method_missing_stub [as $send] (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160518-28384-wfe6i6:996:35)
    at /private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160518-28384-wfe6i6:19450:12
    at Object.<anonymous> (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160518-28384-wfe6i6:19451:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

Although the original example causes a `RangeError: Maximum call stack size exceeded` probably because `#to_s` is used during the generation of the exception. 

Will open a new issue for that, even if it's not top priority.
