### ISSUE TITLE
No Math module

### ISSUE THREAD

**Issue by davispuh** [opal/opal#472]
Seems Math module haven't been implemented.

``` ruby
puts Math.sqrt(9)
```

results in `TypeError: $scope.Math is undefined`

**Comment by PragTob** [comment]
Not sure what I'm doing wrong here but I can't seem to access the `Math` module:

```
tobi@tobi-desktop ~/github/rubykon $ opal -v
Opal v0.8.0
tobi@tobi-desktop ~/github/rubykon $ opal -e "puts Math.sqrt(9)"

/tmp/opal-nodejs-runner-20150927-4619-k8nxau:3611
      throw exception;
            ^
NameError: uninitialized constant Object::Math
    at OpalClass.def.$initialize.self [as $new] (/tmp/opal-nodejs-runner-20150927-4619-k8nxau:3941:15)
    at Opal.defn.self (/tmp/opal-nodejs-runner-20150927-4619-k8nxau:3606:31)
    at def.$const_missing (/tmp/opal-nodejs-runner-20150927-4619-k8nxau:1925:19)
    at Opal.get (/tmp/opal-nodejs-runner-20150927-4619-k8nxau:75:24)
    at Opal.dynamic_require_severity (/tmp/opal-nodejs-runner-20150927-4619-k8nxau:14713:28)
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20150927-4619-k8nxau:14714:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
tobi@tobi-desktop ~/github/rubykon $ ruby -e "puts Math.sqrt(9)"
3.0
```

**Comment by elia** [comment]
The Math module used to be in the stdlib, but has been moved to master after 0.8

https://github.com/opal/opal/blob/master/stdlib/math.rb
