### ISSUE TITLE
Inner class which has JS superclass is exported to outer level

### ISSUE THREAD

**Issue by yhara** [opal/opal#547]
### Example

```
class A
  class B < `Object`
  end
end
p B  #=> Prints `B' instead of `nil'
```

http://opalrb.org/try/#code:class%20A%0A%20%20class%20B%20%3C%20%60Object%60%0A%20%20end%0Aend%0Ap%20B

Also confirmed with opal gem 0.6.2 and opal/opal git master.

### Real world example

* opal-jquery defines `Element`
* [opal-raphael](https://github.com/yhara/opal-raphael) defines `Raphael::Element`
* When you load both of them, `::Element` is overridden by `Raphael::Element`

**Comment by elia** [comment]
Seems to be fixed on master :smile:

```
opal:master ⤑ pbpaste | be bin/opal                                                                                                                                       ~/C/opal

/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4434-putfw2:4361
      throw exception;
      ^
B: uninitialized constant B
    at null.$new (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4434-putfw2:4573:15)
    at ːconst_missing (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4434-putfw2:2518:50)
    at ːconst_get (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4434-putfw2:2495:19)
    at Opal.get (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4434-putfw2:137:24)
    at /private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4434-putfw2:18631:25
    at Object.<anonymous> (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20160402-4434-putfw2:18632:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```
