### ISSUE TITLE
Opal not working for me

### ISSUE THREAD

**Issue by ixixix** [opal/opal#716]
I install opal in ubuntu, normal gem install opal

```
$opal --version
Opal v0.7.1

next i download opal source code and go to the examples sinatra
bundle install and
.../opal/examples/sinatra$bundle exec rackup

/home/user/testo/opal/examples/sinatra/config.ru:9:in `block in <main>': undefined method `source_maps' for #<Opal::Server:0x8b11540> (NoMethodError)
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /home/user/testo/opal/examples/sinatra/config.ru:in `new'
	from /home/user/testo/opal/examples/sinatra/config.ru:in `<main>'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/server.rb:272:in `start'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/lib/rack/server.rb:147:in `start'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/gems/rack-1.6.0/bin/rackup:4:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/bin/rackup:23:in `load'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/bin/rackup:23:in `<main>'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `eval'
	from /home/user/.rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `<main>'


I have trouble with compiling too.
file to convert 
#!/usr/bin/ruby
# encoding: utf-8
require 'opal'

ruby_file = ARGV[0]
parser = Opal::Parser.new
open("#{File.basename(ruby_file,".rb")}.js", "w") do |stream|
  stream.puts parser.parse(File.read(ruby_file))
end

file app.rb
[1, 2, 3].each { |a| puts a }

produce this

call
array
int
1
int
2
int
3
each
arglist
iter
lasgn
a
call

puts
arglist
lvar
a


Gemfile.lock
PATH
  remote: ../..
  specs:
    opal (0.7.1)
      hike (~> 1.2)
      sourcemap (~> 0.1.0)
      sprockets (>= 2.2.3, < 4.0.0)
      tilt (~> 1.4)

GEM
  remote: https://rubygems.org/
  specs:
    hike (1.2.3)
    multi_json (1.10.1)
    rack (1.6.0)
    rack-protection (1.5.3)
      rack
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    sourcemap (0.1.1)
    sprockets (2.12.1)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    tilt (1.4.1)

PLATFORMS
  ruby

DEPENDENCIES
  opal!
  sinatra
```

**Comment by Ajedi32** [comment]
FYI, you can preserve indentation and such in code and log files in your posts on GitHub by indenting it with four spaces, or enclosing it with triple backticks (e.g. ```` ``` ````) on the top and bottom.

Doing that in this post would make your debug output much easier to read.

More info: https://guides.github.com/features/mastering-markdown/

**Comment by elia** [comment]
@ixixix sorry for the delay, you can find the updated config.ru with working sourcemaps here:

https://github.com/opal/opal/blob/485400ecc3196d4c68715a3afdb1f6123ac3a950/examples/sinatra/config.ru
