### ISSUE TITLE
parsing bug on a/(b)

### ISSUE THREAD

**Issue by adrianomitre** [opal/opal#728]
In Opal v0.7.1 fhe following code
```ruby
1.to_f/(2+3)
```
produces the following
```raw
/usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/compiler.rb:140:in `rescue in compile': An error occurred while compiling: ./minimal.rb (RuntimeError)

parse error on value "(" (tLPAREN2) :./minimal.rb:1
Source: ./minimal.rb:1:8
1.to_f/(2+3)
~~~~~~~^
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/compiler.rb:130:in `compile'
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/builder_processors.rb:91:in `compiled'
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/builder_processors.rb:101:in `requires'
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/builder.rb:40:in `build_str'
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/cli.rb:113:in `compiled_source'
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/cli.rb:84:in `run_code'
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/lib/opal/cli.rb:69:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/opal-0.7.1/bin/opal:22:in `<top (required)>'
	from /usr/local/bin/opal:23:in `load'
	from /usr/local/bin/opal:23:in `<main>'
```

Adding whitespace between ```/``` and ```(2+3)``` makes the complaint go away.

**Comment by vais** [comment]
+1 
```
$ bundle exec opal -v -e "1.to_f/(2 + 3)"
Opal v0.7.1
/Users/vais/GitHub/opal/lib/opal/compiler.rb:140:in `rescue in compile': An error occurred while compiling: -e (RuntimeError)

parse error on value "(" (tLPAREN2) :-e:1
Source: -e:1:8
1.to_f/(2 + 3)
~~~~~~~^
	from /Users/vais/GitHub/opal/lib/opal/compiler.rb:130:in `compile'
	from /Users/vais/GitHub/opal/lib/opal/builder_processors.rb:91:in `compiled'
	from /Users/vais/GitHub/opal/lib/opal/builder_processors.rb:101:in `requires'
	from /Users/vais/GitHub/opal/lib/opal/builder.rb:40:in `build_str'
	from /Users/vais/GitHub/opal/lib/opal/cli.rb:110:in `compiled_source'
	from /Users/vais/GitHub/opal/lib/opal/cli.rb:84:in `run_code'
	from /Users/vais/GitHub/opal/lib/opal/cli.rb:69:in `run'
	from /Users/vais/GitHub/opal/bin/opal:22:in `<top (required)>'
	from /Users/vais/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bin/opal:23:in `load'
	from /Users/vais/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bin/opal:23:in `<main>'
$
```
But adding spaces around the `/` works:
```
$ bundle exec opal -v -e "1.to_f / (2 + 3)"
Opal v0.7.1
$
```

**Comment by elia** [comment]
The simplest case I found is `a/(b)`
