### ISSUE TITLE
Module#prepend not implemented

### ISSUE THREAD

**Issue by jxxcarlson** [opal/opal#796]
Rubys' (fantastic new) `prepend` method throws an error.  Just run the exemple of

http://dev.af83.com/2012/10/19/ruby-2-0-module-prepend.html

```
cd /tmp

$ cat >foo.rb

module FooBar
 def hello
   puts 2
   super
 end
end

class Foo
 def hello
   puts 'hello'
 end
end

class Bar < Foo
 prepend FooBar

 def hello
   puts 1
   super
 end
end

Bar.new.hello
```

(2) Run opal on the fie

```
$ opal foo.rb

/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:3041
     throw exception;
           ^
NoMethodError: undefined method `prepend' for Bar
   at OpalClass.$new (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:3361:15)
   at OpalClass.<anonymous> (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:3037:31)
   at OpalClass.Opal.defn.TMP_1 (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:2440:19)
   at OpalClass.method_missing_stub [as $prepend] (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:709:35)
   at /private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:12926:10
   at /private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:12935:5
   at Object.<anonymous> (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:12937:3)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)

```

**Comment by adambeynon** [comment]
Hopefully I will try and fix this for 0.8 release.

Note to self/contributors: fix should be as simple as copying all methods into prototype, same as `Module#include`, except we never override a method already defined by the class or any included modules. We need to set the `$$parent` of the class then to this prepended module to ensure super calls search the chain correctly.

**Comment by jxxcarlson** [comment]
Is there an ETA for 0.8?  We very much need this feature for a projectt we are working on (cross-compilling asciidoctor-latex to javascript so that it can be used in browsers like Chrome, Firefox and edttor like Atom).  See for example

	 http://www.noteshare.io/section/asciidoctor-latex-manual-intro 

or 

	http://noteshare.io/book/transcendental-numbers-and-periods 

I’ll look into prepend myself also, though I’m a noob at this sort of thing.

Thanks!  Opal is awesome!!

**Comment by mojavelinux** [comment]
As more and more libraries are dropping support for Ruby 1.9, this is becoming a bigger issue with compatibility with gems. We'll want to get ahead of this one before it leads to misconceptions about Opal's lack of compatibility with Ruby 2.

**Comment by Papierkorb** [comment]
Any update on this? I'm also interested in using Module#prepend on my end. (And thanks for Opal!)

**Comment by iliabylich** [comment]
Implemented in https://github.com/opal/opal/pull/1826
