### ISSUE TITLE
Class Mismatch

### ISSUE THREAD

**Issue by phase** [opal/opal#808]
I'm trying to convert @mmozuras's [color_difference](https://github.com/mmozuras/color_difference) to JavaScript, and I this file caused a problem for me:
```ruby
module ColorDifference
  class Color < Struct.new(:red, :green, :blue)
    def l
      @l ||= (116.0 * lab_y) - 16.0
    end

    def a
      @a ||= 500.0 * (lab_x - lab_y)
    end

    def b
      @b ||= 200.0 * (lab_y - lab_z)
    end

    def x
      @x ||= 0.4124 * xyz_r + 0.3576 * xyz_g + 0.1805 * xyz_b
    end

    def y
      @y ||= 0.2126 * xyz_r + 0.7152 * xyz_g + 0.0722 * xyz_b
    end

    def z
      @z ||= 0.0193 * xyz_r + 0.1192 * xyz_g + 0.9505 * xyz_b
    end

    private

    def lab_x
      @lab_x ||= lab(x / 95.047)
    end

    def lab_y
      @lab_y ||= lab(y / 100.000)
    end

    def lab_z
      @lab_z ||= lab(z / 108.883)
    end

    def lab(light)
      if light > 0.008856
        light**(1.0 / 3)
      else
        (7.787 * light) + (16.0 / 116)
      end
    end

    def xyz_r
      @xyz_r ||= xyz(red)
    end

    def xyz_g
      @xyz_g ||= xyz(green)
    end

    def xyz_b
      @xyz_b ||= xyz(blue)
    end

    def xyz(light)
      light = light / 255.0
      result = light <= 0.04045 ? light / 12.92 : ((light + 0.055) / 1.055)**2.4
      result * 100
    end
  end
end
```

With the error:
```
TypeError: superclass mismatch for class Color
TypeError: superclass mismatch for class Color
    at t.$new (http://opalrb.org/javascripts/try.js:5:23242)
    at x.klass (http://opalrb.org/javascripts/try.js:4:25667)
    at eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:19:19486), <anonymous>:14:27)
    at eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:19:19486), <anonymous>:114:7)
    at eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:19:19486), <anonymous>:115:5)
    at $TryOpal.eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:19:19486), <anonymous>:116:3)
    at $TryOpal.def.$eval_code (http://opalrb.org/javascripts/try.js:19:19481)
    at $TryOpal.def.$run_code (http://opalrb.org/javascripts/try.js:19:19375)
    at e.$$p.$ (http://opalrb.org/javascripts/try.js:19:18686)
    at HTMLAnchorElement.o (http://opalrb.org/javascripts/try.js:18:28779)

```

Renaming the class solved the issue, but I'm wondering what caused it.

**Comment by elia** [comment]
Sounds like `Color` is already defined with a different superclass, does the code run fine in MRI/cRuby?

**Comment by elia** [comment]
Sorry, discard that, I think you should try from the command line, opalrb.org/try is not supposed to be a converter or compiler but rather a playground (in the lightest sense).

**Comment by elia** [comment]
e.g.

```
gem install opal
opal color.rb

**Comment by elia** [comment]
Ok, just tried locally and seems to work fine, here's how to reproduce:

```
$ gem install opal color_difference
…
$ opal -v -g color_difference -rmath -rcolor_difference -e 'p ColorDifference.cie2000({ r: 255, g: 25, b: 31 }, { r: 251, g: 34, b: 89 })'
Opal v0.7.1
0.13274097039104046
```

The only weird thing is that you need to require `Math` explicitly with `-rmath` because is not part of the corelib but it's in stdlib. Run `opal -h` to get details about all the options used in the example.

**Comment by phase** [comment]
I'm using color_difference for [color-proximity](https://github.com/gjtorikian/color-proximity), how could I include that in the `opal` command?

**Comment by elia** [comment]
Can you give me an example showing how you'd do that in normal Ruby?

**Comment by phase** [comment]
https://github.com/phase/color-check/blob/gh-pages/color.rb Right now I have it all placed in one file. Would this load fine?

**Comment by elia** [comment]
Give it a try and feel free to reopen if you get any errors

**Comment by phase** [comment]
@elia How could I run a method and get the return value through JavaScript?

**Comment by vais** [comment]
@phase To call Ruby from JavaScript:
```
var whatev = #{ruby here};
```
To call JavaScript from Ruby:
```
whatev= `js here`
```
or, for multi-line:
```
ruby
%x{
  js here
}
ruby
```
Unless I totally missed your real question :)

**Comment by phase** [comment]
@vais I've got a class called `ColorProximity`, and I want to call `initialize(threshold, collection)` and `past_threshold?(color)` from JavaScript, since I'm getting another variable from somewhere else.

**Comment by vais** [comment]
@phase you can interleave Ruby and JS like this:
```javascript
var obj = #{ColorProximity.new(`threshold`, `collection`)};
...
var isPastThreshold = #{past_threshold?(`color`)};
```
In the above examples the arguments are JS variables.
Obviously this code would need be run through Opal compiler.

**Comment by phase** [comment]
@vais When using that, I get this:
```
SyntaxError: An error occurred while compiling: (file)

unexpected '"tEH"'
Source: (file):238:911
    var isPastThreshold = #{obj.past_threshold?(a.start_with('#')? ? a : '#'+a};
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
SyntaxError: An error occurred while compiling: (file)

unexpected '"tEH"'
Source: (file):238:911
    var isPastThreshold = #{obj.past_threshold?(a.start_with('#')? ? a : '#'+a};
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    at t.$new (http://opalrb.org/javascripts/try.js:5:23242)
    at i.<anonymous> (http://opalrb.org/javascripts/try.js:5:19362)
    at i._.$compile (http://opalrb.org/javascripts/try.js:18:2113)
    at e.$compile (http://opalrb.org/javascripts/try.js:18:92)
    at $TryOpal.def.$run_code (http://opalrb.org/javascripts/try.js:19:19235)
    at e.$$p.$ (http://opalrb.org/javascripts/try.js:19:18686)
    at HTMLAnchorElement.o (http://opalrb.org/javascripts/try.js:18:28779)
    at HTMLAnchorElement.K.event.dispatch (http://opalrb.org/javascripts/application.js:3:4882)
    at HTMLAnchorElement.s.handle.a (http://opalrb.org/javascripts/application.js:3:782)

```

**Comment by vais** [comment]
@phase there's a couple things wrong with that line of code:
1. `a.start_with('#')?` should be `a.start_with?('#')`
2. the number of closing parens does not match up with the number of opening parens
