### ISSUE TITLE
`call { true or next }` produces invalid js

### ISSUE THREAD

**Issue by elia** [opal/opal#810]
```
> opal -e 'call { true or next }'
/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20150424-87011-ohchab:14182
  return ((($a = true) !== false && $a !== nil) ? $a : return nil;)}, TMP_1.$$
                                                       ^^^^^^
SyntaxError: Unexpected token return
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Similar/duplicate issues that make for additional test cases are: https://github.com/opal/opal/issues/1492 https://github.com/opal/opal/issues/2091 https://github.com/opal/opal/issues/2103

**Comment by elia** [comment]
the produced js code is:

`> opal -Oce 'call { true or next }'`
```js
/* Generated by Opal 0.8.0.dev */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var $a, $b, TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$call']);
  return ($a = ($b = self).$call, $a.$$p = (TMP_1 = function(){var self = TMP_1.$$s || this, $a;

  return ((($a = true) !== false && $a !== nil) ? $a : return nil;)}, TMP_1.$$s = self, TMP_1), $a).call($b)
})(Opal);

/* Generated by Opal 0.8.0.dev */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$exit']);
  return $scope.get('Kernel').$exit()
})(Opal);
```

**Comment by elia** [comment]
another incarnation from #1492: `foo and next if bar`
