### ISSUE TITLE
Backslash for line continuation does not work

### ISSUE THREAD

**Issue by vais** [opal/opal#821]
```
$ cat test.rb 
a = "a"
b = "b"
puts a == \
  b
```
```
$ bundle exec opal test.rb 

/private/var/folders/pt/kr0lwm4d20jgc_jvpc5fyk1r0000gn/T/opal-nodejs-runner-20150430-1056-wi8a05:14300
  return self.$puts(a['$=='](self.$\
                                  ^^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by vais** [comment]
But the following works:
```
$ cat test.rb 
e = 8 + 9 \
    + 10
puts e
```
```
$ bundle exec opal test.rb 
27
```
Looks like the issue is specifically with a backslash following `==`

**Comment by wied03** [comment]
@vais - Same error happens in rspec's spec code:
```ruby
expect(group.examples.first.exception.message).to \
          match(/may not be used outside of examples/)
```

**Comment by vais** [comment]
@wied03 I couldn't figure it out, need @adambeynon's help on this one.

**Comment by wied03** [comment]
Another case that doesn't work, I noticed while foolishly trying to make the entire activesupport lib work in Opal:

```ruby
def advance(options)
    unless options[:weeks].nil?
      options[:weeks], partial_weeks = options[:weeks].divmod(1)
      options[:days] = options.fetch(:days, 0) + 7 * partial_weeks
    end

    unless options[:days].nil?
      options[:days], partial_days = options[:days].divmod(1)
      options[:hours] = options.fetch(:hours, 0) + 24 * partial_days
    end

    d = to_date.advance(options)
    datetime_advanced_by_date = change(:year => d.year, :month => d.month, :day => d.day)
    seconds_to_advance = \
      options.fetch(:seconds, 0) +
      options.fetch(:minutes, 0) * 60 +
      options.fetch(:hours, 0) * 3600

    if seconds_to_advance.zero?
      datetime_advanced_by_date
    else
      datetime_advanced_by_date.since(seconds_to_advance)
    end
  end
```

**Comment by vais** [comment]
@iliabylich I believe this one can be closed now, could you please confirm?

**Comment by iliabylich** [comment]
Yes, all of these examples can be correctly compiled now, we can close it

**Comment by vais** [comment]
Thank you @iliabylich!
