### ISSUE TITLE
Define_method fails when a Method/UnboundMethod object is supplied

### ISSUE THREAD

**Issue by wied03** [opal/opal#850]
This problem seems too simple so I must be missing something, but when trying to use define_method (http://ruby-doc.org/core-2.2.2/Module.html#method-i-define_method), if you supply a Method/UnboundMethod instead of a block, which is valid behavior, you get a **wrong argument type (expected Proc/Method)** error.

The error message (module.rb line 290) notes that a method might be expected so it seems right but the if statement does not account for that.

This prevents rspec-mocks (via the opal-rspec project) from working in 0.8.

Observed in 0.8.0 beta 1 and I believe the problem is still in Master.

Replicated the UnboundMethod case using http://opalrb.org/try:
```
class A
  def fred
    puts "In Fred"
  end
  def create_method(name, &block)
    self.class.send(:define_method, name, &block)
  end
  define_method(:wilma) { puts "Charge it!" }
end
class B < A
  define_method(:barney, instance_method(:fred))
end
a = B.new
a.barney
a.wilma
a.create_method(:betty) { p self }
a.betty
```
Output:
```
TypeError: wrong argument type UnboundMethod (expected Proc/Method)
TypeError: wrong argument type UnboundMethod (expected Proc/Method)
    at t.$new (http://opalrb.org/javascripts/try.js:5:30463)
    at t.<anonymous> (http://opalrb.org/javascripts/try.js:5:26369)
    at t.c.$define_method.a [as $define_method] (http://opalrb.org/javascripts/try.js:5:5536)
    at eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:20:27290), <anonymous>:36:17)
    at eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:20:27290), <anonymous>:37:5)
    at $TryOpal.eval (eval at <anonymous> (http://opalrb.org/javascripts/try.js:20:27290), <anonymous>:45:3)
    at $TryOpal.def.$eval_code (http://opalrb.org/javascripts/try.js:20:27285)
    at $TryOpal.def.$run_code (http://opalrb.org/javascripts/try.js:20:27179)
    at e.$$p.$ (http://opalrb.org/javascripts/try.js:20:26490)
    at HTMLAnchorElement.o (http://opalrb.org/javascripts/try.js:20:2768)
```
I'll work on a fix/pull request.

**Comment by wied03** [comment]
Created pull request https://github.com/opal/opal/pull/853
