### ISSUE TITLE
etc.so issues

### ISSUE THREAD

**Issue by cj** [opal/opal#880]
I'm trying to run https://github.com/skofo/opal-minitest.  With opal 0.7.2 I get:

```
Error: ArgumentError: An error occurred while compiling: etc.so
invalid byte sequence in UTF-8
  (in /home/cj/gems/wedge/.bundle/gems/opal-0.7.2/stdlib/minitest.rb)

    http://localhost:2838/assets/opal/minitest/loader.js:1
```

With 0.8.0 beta 1 I get:

```
Sprockets::FileNotFound: couldn't find file 'etc.so' with type 'application/javascript'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/resolve.rb:64:in `resolve!'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/context.rb:88:in `resolve'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/legacy.rb:259:in `resolve_with_compat'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/context.rb:142:in `require_asset'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/processor.rb:68:in `block in process_requires'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/processor.rb:66:in `each'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/processor.rb:66:in `process_requires'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/processor.rb:45:in `evaluate'
  /home/cj/gems/wedge/.bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:45:in `block in load'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:156:in `fetch_asset_from_dependency_cache'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:38:in `load'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:47:in `yield'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:47:in `load'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/bundle.rb:23:in `block in call'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/utils.rb:183:in `dfs'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/bundle.rb:24:in `call'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:45:in `block in load'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:156:in `fetch_asset_from_dependency_cache'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/loader.rb:38:in `load'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:47:in `yield'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:47:in `load'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/base.rb:63:in `find_asset'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/environment.rb:30:in `find_asset'
  /home/cj/gems/wedge/.bundle/gems/sprockets-3.1.0/lib/sprockets/base.rb:89:in `[]'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/server.rb:127:in `javascript_include_tag'
  /home/cj/gems/wedge/.bundle/gems/opal-minitest-0.0.4/opal/opal/minitest/runner.html.erb:7:in `block in singleton class'
  /home/cj/gems/wedge/.bundle/gems/opal-minitest-0.0.4/opal/opal/minitest/runner.html.erb:-5:in `instance_eval'
  /home/cj/gems/wedge/.bundle/gems/opal-minitest-0.0.4/opal/opal/minitest/runner.html.erb:-5:in `singleton class'
  /home/cj/gems/wedge/.bundle/gems/opal-minitest-0.0.4/opal/opal/minitest/runner.html.erb:-7:in `__tilt_70182069878120'
  /home/cj/gems/wedge/.bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
  /home/cj/gems/wedge/.bundle/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
  /home/cj/gems/wedge/.bundle/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/server.rb:118:in `html'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/server.rb:108:in `call'
  /home/cj/gems/wedge/.bundle/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
  /home/cj/gems/wedge/.bundle/gems/rack-1.6.0/lib/rack/deflater.rb:35:in `call'
  /home/cj/gems/wedge/.bundle/bundler/gems/opal-9933c666c7dd/lib/opal/sprockets/server.rb:95:in `call'
  /home/cj/gems/wedge/.bundle/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
  /home/cj/.rbenv/versions/2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /home/cj/.rbenv/versions/2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /home/cj/.rbenv/versions/2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

Has anyone else had this issue?

**Comment by elia** [comment]
Please try again with the released version of v0.7.2.
Opal 0.7 series doesn't support sprockets 3, so maybe that's the problem.

**Comment by cj** [comment]
I tried with 0.7.2, which down graded sprockets to 2 but I got this error:

```
Error: ArgumentError: An error occurred while compiling: etc.so
invalid byte sequence in UTF-8
  (in /home/cj/gems/wedge/.bundle/gems/opal-0.7.2/stdlib/minitest.rb)

    http://localhost:2838/assets/opal/minitest/loader.js:1
```

**Comment by elia** [comment]
:disappointed: sorry, missed that, should be fixed on master.

**Comment by cj** [comment]
Cheers, no worries.  Thanks for removing that.  Now I just need to update the opal-mintest lib to stop getting this `NameError: uninitialized constant Object::Minitest`
