### ISSUE TITLE
Parse error on leading splat in method definition

### ISSUE THREAD

**Issue by vais** [opal/opal#939]
@adambeynon each of the following currently fails to parse:
```ruby
def one_splat_one_req(*a,b); end
def one_splat_two_req(*a,b,c); end
def one_splat_one_req_with_block(*a,b,&blk); end
```
E.g.:
```
$ bundle exec opal -ve "def one_splat_one_req(*a,b); end"
Opal v0.8.0.rc1
/Users/vais/GitHub/opal/lib/opal/parser.rb:81:in `on_error': An error occurred while compiling: -e (RuntimeError)

parse error on value "b" (tIDENTIFIER) :-e:1
Source: -e:1:26
def one_splat_one_req(*a,b); end
~~~~~~~~~~~~~~~~~~~~~~~~~^
	from /Users/vais/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/racc-1.4.12/lib/racc/parser.rb:271:in `_racc_do_parse_c'
	from /Users/vais/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/racc-1.4.12/lib/racc/parser.rb:271:in `do_parse'
	from /Users/vais/GitHub/opal/lib/opal/parser.rb:53:in `parse_to_sexp'
	from /Users/vais/GitHub/opal/lib/opal/parser.rb:38:in `parse'
	from /Users/vais/GitHub/opal/lib/opal/compiler.rb:135:in `compile'
	from /Users/vais/GitHub/opal/lib/opal/builder_processors.rb:91:in `compiled'
	from /Users/vais/GitHub/opal/lib/opal/builder_processors.rb:101:in `requires'
	from /Users/vais/GitHub/opal/lib/opal/builder.rb:41:in `build_str'
	from /Users/vais/GitHub/opal/lib/opal/cli.rb:109:in `build'
	from /Users/vais/GitHub/opal/lib/opal/cli.rb:122:in `compiled_source'
	from /Users/vais/GitHub/opal/lib/opal/cli.rb:84:in `run_code'
	from /Users/vais/GitHub/opal/lib/opal/cli.rb:69:in `run'
	from /Users/vais/GitHub/opal/bin/opal:22:in `<top (required)>'
	from /Users/vais/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/opal:23:in `load'
	from /Users/vais/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/opal:23:in `<main>'
```
Any plans to support this in Opal? :pray:

**Comment by adambeynon** [comment]
@vais Yes, this has been missing for too long. We need to restructure the code generation part for method definitions, as well as method calls that can pass args after a splat. This is likely to be after 0.8 though. I suspect it will involve a lot of rewriting of code generation classes.

**Comment by elia** [comment]
cc @alexdowad :)

**Comment by vais** [comment]
@iliabylich do you think this can be closed now?

**Comment by iliabylich** [comment]
@vais  Only after merging #1395 (which is not quite ready yet)

**Comment by elia** [comment]
I suppose this can be closed now :smile: 

props to @iliabylich for making it happen!

```js
⤑ pbpaste | opal -cEO                                                                                                ~
/* Generated by Opal 0.10.0.beta2 */
(function(Opal) {
  var TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.defn(Opal.Object, '$one_splat_one_req', function ːone_splat_one_req($a_rest, $b) {
    var self = this, $post_args, a, b;

    $post_args = Opal.slice.call(arguments, 0, arguments.length);
    if (1 < $post_args.length) {
      a = $post_args.splice(0, $post_args.length - 1);
    } else {
      a = [];
    }
    b = $post_args.splice(0,1)[0];
    return nil;
  });
  Opal.defn(Opal.Object, '$one_splat_two_req', function ːone_splat_two_req($a_rest, $b, $c) {
    var self = this, $post_args, a, b, c;

    $post_args = Opal.slice.call(arguments, 0, arguments.length);
    if (2 < $post_args.length) {
      a = $post_args.splice(0, $post_args.length - 2);
    } else {
      a = [];
    }
    b = $post_args.splice(0,1)[0];
    c = $post_args.splice(0,1)[0];
    return nil;
  });
  return (Opal.defn(Opal.Object, '$one_splat_one_req_with_block', TMP_1 = function ːone_splat_one_req_with_block($a_rest, $b) {
    var self = this, $post_args, a, b, $iter = TMP_1.$$p, blk = $iter || nil;

    $post_args = Opal.slice.call(arguments, 0, arguments.length);
    if (1 < $post_args.length) {
      a = $post_args.splice(0, $post_args.length - 1);
    } else {
      a = [];
    }
    b = $post_args.splice(0,1)[0];
    TMP_1.$$p = null;
    return nil;
  }), nil) && 'one_splat_one_req_with_block';
})(Opal);
```
