### ISSUE TITLE
issue passing &block to def []

### ISSUE THREAD

**Issue by cj** [opal/opal#959]
http://goo.gl/xDTGID

**Comment by cj** [comment]
```
SyntaxError: An error occurred while compiling: (file)

unexpected '"tAMPER"'
Source: (file):10:15
  User[*args, &block]
~~~~~~~~~~~~~~^
SyntaxError: An error occurred while compiling: (file)

unexpected '"tAMPER"'
Source: (file):10:15
  User[*args, &block]
~~~~~~~~~~~~~~^
    at t.$new (http://opalrb.org/javascripts/try.js:5:30463)
    at a.<anonymous> (http://opalrb.org/javascripts/try.js:5:26369)
    at a.d.$compile (http://opalrb.org/javascripts/try.js:19:4138)
    at e.$compile (http://opalrb.org/javascripts/try.js:19:2017)
    at $TryOpal.def.$run_code (http://opalrb.org/javascripts/try.js:20:27039)
    at HTMLDocument.$a.$$p.TMP_3 (http://opalrb.org/javascripts/try.js:20:28057)
    at f (http://opalrb.org/javascripts/application.js:2:16766)
    at Object.p.fireWith [as resolveWith] (http://opalrb.org/javascripts/application.js:2:17547)
    at Function.K.extend.ready (http://opalrb.org/javascripts/application.js:2:12308)
    at HTMLDocument.pt (http://opalrb.org/javascripts/application.js:2:9736)
```

**Comment by cj** [comment]
@elia any chance on getting this added to the `0.9` milestone?

**Comment by alexdowad** [comment]
@elia's new thing for parser debugging is working great! I've found that the token the parser is failing on is `tAMPER`. When successfully parsing something like `method(*args, &block)`, the part with the ampersand reduces to `block_arg` via `block_arg : tAMPER arg_value`, from there via `opt_block_arg : tCOMMA block_arg`, from there via `call_args : args opt_block_arg`.

It looks like calls which use the `receiver[ ... ]` syntax use `aref_args`, not `call_args`. Just having a look at those rules...

**Comment by alexdowad** [comment]
I've added a new rule which allows the parser to parse a trailing `, &block` argument in an aref. Not sure  yet if the compiler will freak out.

**Comment by alexdowad** [comment]
Wow, the compiler just eats this code up! Success!

**Comment by elia** [comment]
w00t!1
