### ISSUE TITLE
Opal compiled javascript does not work in nodejs CLI

### ISSUE THREAD

**Issue by tymat** [opal/opal#966]
I have this simple ruby class:
```ruby
class SomeContract
  attr_accessor :name, :email, :password

  def initialize
    @name = "foo"
    @email = "bar@fizz"
    @password = "baz"
  end

  def contactinfo
    puts "#{@name} <#{@email}>"
  end

  def authenticate(password)
    password == @password
  end

end
```

Compiled on the shell then tried to load the file on node CLI:

```bash
$ opal -rnodejs -c sample.rb > sample.js
$ node
```
```javascript
> var glob = require('glob')
undefined
> var Opal = require('./sample.js')
$
```

Added --no-exit flag

```bash
$ opal --no-exit -rnodejs -c sample.rb > sample.js
$ node
```

```javascript
> var glob = require('glob')
undefined
> var Opal = require('./sample.js')
undefined
> var b = Opal.SomeContract.$new()
TypeError: Cannot read property '$new' of undefined
    at repl:1:26
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
```

**Comment by tymat** [comment]
This works on the browser console as a script \<src="sample.js"\> in an HTML 

```bash
$ opal -c sample.rb > sample.js
```

Some environment information
```
$ opal --version
Opal v0.7.2

$ node -v
v0.12.2

$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

$ uname -a
Darwin kingmob 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by elia** [comment]
Opal by Ruby's nature is global even in nodejs, so instead of assigning to `var Opal` the result of `require('./sample.js')` you just require it.

After the require `Opal` is available as a property of the global object and then `Opal.SomeContract.$new()` works.

Actually the result of `require('./sample.js')` is an object with the `Opal` property, maybe that can be changed to just return `Opal`. wdyt?

**Comment by elia** [comment]
Closing as stale, feel free to ping me to reopen.
